/*
 *  Generated by LwipMibCompiler
 */

#ifndef NTCIP_1201V0307_H
#define NTCIP_1201V0307_H NTCIP_1201V0307_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp_core.h"

extern const struct snmp_mib globalconfiguration;

extern const struct snmp_mib globaldbmanagement;

extern const struct snmp_mib globaltimemanagement;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP */
#endif /* NTCIP_1201V0307_H */
