/*
 *  Generated by LwipMibCompiler
 */

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP
#include <string.h>
#include "1201v0307.h"
#include "lwip/apps/snmp.h"
#include "lwip/apps/snmp_core.h"
#include "lwip/apps/snmp_scalar.h"
#include "lwip/apps/snmp_table.h"

#include "data.h"
#include "PPPOSAsynch.h"
/* --- globalConfiguration  ----------------------------------------------------- */
static s16_t globalconfiguration_root_get_value(
  struct snmp_node_instance *instance,
  void *value);

static const struct snmp_scalar_node globalsetidparameter_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(1,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   globalconfiguration_root_get_value);

static const struct snmp_scalar_node globalmaxmodules_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(2,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   globalconfiguration_root_get_value);

static snmp_err_t globalmoduletable_get_instance(const u32_t *column,
                                                 const u32_t *row_oid,
                                                 u8_t row_oid_len,
                                                 struct snmp_node_instance *
                                                 cell_instance);
static snmp_err_t globalmoduletable_get_next_instance(const u32_t *column,
                                                      struct snmp_obj_id *
                                                      row_oid,
                                                      struct snmp_node_instance
                                                      *cell_instance);
static s16_t globalmoduletable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value);

static const struct snmp_table_col_def globalmoduletable_columns[] = { { 1,
                                                                         SNMP_ASN1_TYPE_INTEGER,
                                                                         SNMP_NODE_INSTANCE_READ_ONLY },
                                                                       /* moduleNumber */
                                                                       { 2,
                                                                         SNMP_ASN1_TYPE_OBJECT_ID,
                                                                         SNMP_NODE_INSTANCE_READ_ONLY },
                                                                       /* moduleDeviceNode */
                                                                       { 3,
                                                                         SNMP_ASN1_TYPE_OCTET_STRING,
                                                                         SNMP_NODE_INSTANCE_READ_ONLY },
                                                                       /* moduleMake */
                                                                       { 4,
                                                                         SNMP_ASN1_TYPE_OCTET_STRING,
                                                                         SNMP_NODE_INSTANCE_READ_ONLY },
                                                                       /* moduleModel */
                                                                       { 5,
                                                                         SNMP_ASN1_TYPE_OCTET_STRING,
                                                                         SNMP_NODE_INSTANCE_READ_ONLY },
                                                                       /* moduleVersion */
                                                                       { 6,
                                                                         SNMP_ASN1_TYPE_INTEGER,
                                                                         SNMP_NODE_INSTANCE_READ_ONLY },
                                                                       /* moduleType */
};
static const struct snmp_table_node globalmoduletable =
  SNMP_TABLE_CREATE(3,
                    globalmoduletable_columns,
                    globalmoduletable_get_instance,
                    globalmoduletable_get_next_instance,
                    globalmoduletable_get_value,
                    NULL,
                    NULL)
;

static const struct snmp_scalar_node controllerbasestandards_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(4,
                                   SNMP_ASN1_TYPE_OCTET_STRING,
                                   globalconfiguration_root_get_value);

static const struct snmp_node *const globalconfiguration_subnodes[] =
{ &globalsetidparameter_scalar.node.node,
  &
  globalmaxmodules_scalar.node.node,
  &
  globalmoduletable.node.node,
  &
  controllerbasestandards_scalar.node.node };
static const struct snmp_tree_node globalconfiguration_root =
  SNMP_CREATE_TREE_NODE(1, globalconfiguration_subnodes);
static const u32_t globalconfiguration_base_oid[] = { 1, 3, 6, 1, 4, 1, 1206, 4,
                                                      2, 6, 1 };
const struct snmp_mib globalconfiguration = { globalconfiguration_base_oid,
                                              LWIP_ARRAYSIZE(
                                                globalconfiguration_base_oid),
                                              &globalconfiguration_root.node };

/* --- globalDBManagement  ----------------------------------------------------- */
static s16_t globaldbmanagement_root_get_value(
  struct snmp_node_instance *instance,
  void *value);
static snmp_err_t globaldbmanagement_root_set_test(
  struct snmp_node_instance *instance,
  u16_t len,
  void *value);
static snmp_err_t globaldbmanagement_root_set_value(
  struct snmp_node_instance *instance,
  u16_t len,
  void *value);

static const struct snmp_scalar_node dbcreatetransaction_scalar =
  SNMP_SCALAR_CREATE_NODE(1,
                          SNMP_NODE_INSTANCE_READ_WRITE,
                          SNMP_ASN1_TYPE_INTEGER,
                          globaldbmanagement_root_get_value,
                          globaldbmanagement_root_set_test,
                          globaldbmanagement_root_set_value)
;

static const struct snmp_scalar_node dberrortype_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(2,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   globaldbmanagement_root_get_value);

static const struct snmp_scalar_node dberrorid_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(3,
                                   SNMP_ASN1_TYPE_OBJECT_ID,
                                   globaldbmanagement_root_get_value);

static const struct snmp_scalar_node dbtransactionid_scalar =
  SNMP_SCALAR_CREATE_NODE(4,
                          SNMP_NODE_INSTANCE_READ_WRITE,
                          SNMP_ASN1_TYPE_INTEGER,
                          globaldbmanagement_root_get_value,
                          globaldbmanagement_root_set_test,
                          globaldbmanagement_root_set_value)
;

static const struct snmp_scalar_node dbmakeid_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(5,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   globaldbmanagement_root_get_value);

static const struct snmp_scalar_node dbverifystatus_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(6,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   globaldbmanagement_root_get_value);

static const struct snmp_scalar_node dbverifyerror_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(7,
                                   SNMP_ASN1_TYPE_OCTET_STRING,
                                   globaldbmanagement_root_get_value);

static const struct snmp_node *const globaldbmanagement_subnodes[] =
{ &dbcreatetransaction_scalar.node.node,
  &
  dberrortype_scalar.node.node, &dberrorid_scalar
  .node.
  node,
  &
  dbtransactionid_scalar.node.node,
  &
  dbmakeid_scalar.node.node,
  &
  dbverifystatus_scalar.node.node,
  &
  dbverifyerror_scalar.node.node };
static const struct snmp_tree_node globaldbmanagement_root =
  SNMP_CREATE_TREE_NODE(2, globaldbmanagement_subnodes);
static const u32_t globaldbmanagement_base_oid[] = { 1, 3, 6, 1, 4, 1, 1206, 4,
                                                     2, 6, 2 };
const struct snmp_mib globaldbmanagement = { globaldbmanagement_base_oid,
                                             LWIP_ARRAYSIZE(
                                               globaldbmanagement_base_oid),
                                             &globaldbmanagement_root.node };

/* --- timebase 1,3,6,1,4,1,1206,4,2,6,3,3 ----------------------------------------------------- */
static s16_t timebase_treenode_get_value(struct snmp_node_instance *instance,
                                         void *value);

static const struct snmp_scalar_node maxtimebasescheduleentries_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(1,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   timebase_treenode_get_value);

static snmp_err_t timebasescheduletable_get_instance(const u32_t *column,
                                                     const u32_t *row_oid,
                                                     u8_t row_oid_len,
                                                     struct snmp_node_instance *
                                                     cell_instance);
static snmp_err_t timebasescheduletable_get_next_instance(const u32_t *column,
                                                          struct snmp_obj_id *
                                                          row_oid,
                                                          struct
                                                          snmp_node_instance *
                                                          cell_instance);
static s16_t timebasescheduletable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value);
static snmp_err_t timebasescheduletable_set_test(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value);
static snmp_err_t timebasescheduletable_set_value(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value);

static const struct snmp_table_col_def timebasescheduletable_columns[] = { { 1,
                                                                             SNMP_ASN1_TYPE_INTEGER,
                                                                             SNMP_NODE_INSTANCE_READ_ONLY },
                                                                           /* timeBaseScheduleNumber */
                                                                           { 2,
                                                                             SNMP_ASN1_TYPE_INTEGER,
                                                                             SNMP_NODE_INSTANCE_READ_WRITE },
                                                                           /* timeBaseScheduleMonth */
                                                                           { 3,
                                                                             SNMP_ASN1_TYPE_INTEGER,
                                                                             SNMP_NODE_INSTANCE_READ_WRITE },
                                                                           /* timeBaseScheduleDay */
                                                                           { 4,
                                                                             SNMP_ASN1_TYPE_COUNTER,
                                                                             SNMP_NODE_INSTANCE_READ_WRITE },
                                                                           /* timeBaseScheduleDate */
                                                                           { 5,
                                                                             SNMP_ASN1_TYPE_INTEGER,
                                                                             SNMP_NODE_INSTANCE_READ_WRITE },
                                                                           /* timeBaseScheduleDayPlan */
};
static const struct snmp_table_node timebasescheduletable =
  SNMP_TABLE_CREATE(2,
                    timebasescheduletable_columns,
                    timebasescheduletable_get_instance,
                    timebasescheduletable_get_next_instance,
                    timebasescheduletable_get_value,
                    timebasescheduletable_set_test,
                    timebasescheduletable_set_value)
;

static const struct snmp_scalar_node maxdayplans_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(3,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   timebase_treenode_get_value);

static const struct snmp_scalar_node maxdayplanevents_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(4,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   timebase_treenode_get_value);

static snmp_err_t timebasedayplantable_get_instance(const u32_t *column,
                                                    const u32_t *row_oid,
                                                    u8_t row_oid_len,
                                                    struct snmp_node_instance *
                                                    cell_instance);
static snmp_err_t timebasedayplantable_get_next_instance(const u32_t *column,
                                                         struct snmp_obj_id *
                                                         row_oid,
                                                         struct
                                                         snmp_node_instance *
                                                         cell_instance);
static s16_t timebasedayplantable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value);
static snmp_err_t timebasedayplantable_set_test(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value);
static snmp_err_t timebasedayplantable_set_value(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value);

static const struct snmp_table_col_def timebasedayplantable_columns[] = { { 1,
                                                                            SNMP_ASN1_TYPE_INTEGER,
                                                                            SNMP_NODE_INSTANCE_READ_ONLY },
                                                                          /* dayPlanNumber */
                                                                          { 2,
                                                                            SNMP_ASN1_TYPE_INTEGER,
                                                                            SNMP_NODE_INSTANCE_READ_ONLY },
                                                                          /* dayPlanEventNumber */
                                                                          { 3,
                                                                            SNMP_ASN1_TYPE_INTEGER,
                                                                            SNMP_NODE_INSTANCE_READ_WRITE },
                                                                          /* dayPlanHour */
                                                                          { 4,
                                                                            SNMP_ASN1_TYPE_INTEGER,
                                                                            SNMP_NODE_INSTANCE_READ_WRITE },
                                                                          /* dayPlanMinute */
                                                                          { 5,
                                                                            SNMP_ASN1_TYPE_OBJECT_ID,
                                                                            SNMP_NODE_INSTANCE_READ_WRITE },
                                                                          /* dayPlanActionNumberOID */
};
static const struct snmp_table_node timebasedayplantable =
  SNMP_TABLE_CREATE(5,
                    timebasedayplantable_columns,
                    timebasedayplantable_get_instance,
                    timebasedayplantable_get_next_instance,
                    timebasedayplantable_get_value,
                    timebasedayplantable_set_test,
                    timebasedayplantable_set_value)
;

static const struct snmp_scalar_node dayplanstatus_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(6,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   timebase_treenode_get_value);

static const struct snmp_scalar_node timebasescheduletablestatus_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(7,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   timebase_treenode_get_value);

static const struct snmp_node *const timebase_subnodes[] =
{ &maxtimebasescheduleentries_scalar.node.node,
  &
  timebasescheduletable.node.node, &maxdayplans_scalar.node
  .node,
  &
  maxdayplanevents_scalar.node.node, &timebasedayplantable
  .node.node,
  &
  dayplanstatus_scalar.node.node,
  &
  timebasescheduletablestatus_scalar.node.node };
static const struct snmp_tree_node timebase_treenode = SNMP_CREATE_TREE_NODE(3,
                                                                             timebase_subnodes);

/* --- daylightSavingNode 1,3,6,1,4,1,1206,4,2,6,3,7 ----------------------------------------------------- */
static s16_t maxDaylightSavingEntries_get_value(
  struct snmp_node_instance *instance,
  void *value);

static const struct snmp_scalar_node maxdaylightsavingentries_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(1,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   maxDaylightSavingEntries_get_value);

static snmp_err_t dsttable_get_instance(const u32_t *column,
                                        const u32_t *row_oid,
                                        u8_t row_oid_len,
                                        struct snmp_node_instance *cell_instance);
static snmp_err_t dsttable_get_next_instance(const u32_t *column,
                                             struct snmp_obj_id *row_oid,
                                             struct snmp_node_instance *
                                             cell_instance);
static s16_t dsttable_get_value(struct snmp_node_instance *cell_instance,
                                void *value);
static snmp_err_t dsttable_set_test(struct snmp_node_instance *cell_instance,
                                    u16_t len,
                                    void *value);
static snmp_err_t dsttable_set_value(struct snmp_node_instance *cell_instance,
                                     u16_t len,
                                     void *value);

static const struct snmp_table_col_def dsttable_columns[] = {
  { 1, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY },   /* dstEntryNumber */
  { 2, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE },   /* dstBeginMonth */
  { 3, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE },   /* dstBeginOccurrences */
  { 4, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE },   /* dstBeginDayOfWeek */
  { 5, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE },   /* dstBeginDayOfMonth */
  { 6, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_WRITE },   /* dstBeginSecondsToTransition */
  { 7, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE },   /* dstEndMonth */
  { 8, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE },   /* dstEndOccurrences */
  { 9, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE },   /* dstEndDayOfWeek */
  { 10, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE },   /* dstEndDayOfMonth */
  { 11, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_WRITE },   /* dstEndSecondsToTransition */
  { 12, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE },   /* dstSecondsToAdjust */
};
static const struct snmp_table_node dsttable =
  SNMP_TABLE_CREATE(2,
                    dsttable_columns,
                    dsttable_get_instance,
                    dsttable_get_next_instance,
                    dsttable_get_value,
                    dsttable_set_test,
                    dsttable_set_value)
;

static const struct snmp_node *const daylightsavingnode_subnodes[] =
{ &maxdaylightsavingentries_scalar.node.node,
  &dsttable
  .node.node };
static const struct snmp_tree_node daylightsavingnode_treenode =
  SNMP_CREATE_TREE_NODE(7, daylightsavingnode_subnodes);

/* --- globalTimeManagement  ----------------------------------------------------- */
static s16_t globaltimemanagement_root_get_value(
  struct snmp_node_instance *instance,
  void *value);
static snmp_err_t globaltimemanagement_root_set_test(
  struct snmp_node_instance *instance,
  u16_t len,
  void *value);
static snmp_err_t globaltimemanagement_root_set_value(
  struct snmp_node_instance *instance,
  u16_t len,
  void *value);

static const struct snmp_scalar_node globaltime_scalar =
  SNMP_SCALAR_CREATE_NODE(1,
                          SNMP_NODE_INSTANCE_READ_WRITE,
                          SNMP_ASN1_TYPE_COUNTER,
                          globaltimemanagement_root_get_value,
                          globaltimemanagement_root_set_test,
                          globaltimemanagement_root_set_value)
;

static const struct snmp_scalar_node globaldaylightsaving_scalar =
  SNMP_SCALAR_CREATE_NODE(2,
                          SNMP_NODE_INSTANCE_READ_WRITE,
                          SNMP_ASN1_TYPE_INTEGER,
                          globaltimemanagement_root_get_value,
                          globaltimemanagement_root_set_test,
                          globaltimemanagement_root_set_value)
;

static const struct snmp_scalar_node globallocaltimedifferential_scalar =
  SNMP_SCALAR_CREATE_NODE(4,
                          SNMP_NODE_INSTANCE_READ_WRITE,
                          SNMP_ASN1_TYPE_INTEGER,
                          globaltimemanagement_root_get_value,
                          globaltimemanagement_root_set_test,
                          globaltimemanagement_root_set_value)
;

static const struct snmp_scalar_node controllerstandardtimezone_scalar =
  SNMP_SCALAR_CREATE_NODE(5,
                          SNMP_NODE_INSTANCE_READ_WRITE,
                          SNMP_ASN1_TYPE_INTEGER,
                          globaltimemanagement_root_get_value,
                          globaltimemanagement_root_set_test,
                          globaltimemanagement_root_set_value)
;

static const struct snmp_scalar_node controllerlocaltime_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(6,
                                   SNMP_ASN1_TYPE_COUNTER,
                                   globaltimemanagement_root_get_value);

static const struct snmp_node *const globaltimemanagement_subnodes[] =
{ &globaltime_scalar.node.node,
  &
  globaldaylightsaving_scalar.node.node,
  &
  timebase_treenode.node,
  &
  globallocaltimedifferential_scalar.node.node,
  &
  controllerstandardtimezone_scalar.node.node,
  &
  controllerlocaltime_scalar.node.node,
  &
  daylightsavingnode_treenode.node };
static const struct snmp_tree_node globaltimemanagement_root =
  SNMP_CREATE_TREE_NODE(3, globaltimemanagement_subnodes);
static const u32_t globaltimemanagement_base_oid[] = { 1, 3, 6, 1, 4, 1, 1206,
                                                       4, 2, 6, 3 };
const struct snmp_mib globaltimemanagement = { globaltimemanagement_base_oid,
                                               LWIP_ARRAYSIZE(
                                                 globaltimemanagement_base_oid),
                                               &globaltimemanagement_root.node };

/*
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 +  LWIP MIB generator - preserved section begin
 +  Code below is preserved on regeneration. Remove these comment lines to regenerate code.
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 */
static const struct snmp_oid_range global_module_table_oid_ranges[] = { { 1,
                                                                          GLOBAL_CONFIG_MAX_MODULES } };

static const struct snmp_oid_range dst_table_oid_ranges[] = { { 1,
                                                                GTM_DAYLIGHT_SAVINGS_MAX } };

static const struct snmp_oid_range time_base_schedule_table_oid_ranges[] =
{ { 1, GTM_TIME_BASE_MAX_SCHEDULES } };

static const struct snmp_oid_range time_base_day_plan_table_oid_ranges[] =
{ { 1, GTM_TIME_BASE_MAX_DAY_PLANS }, {
    1,
    GTM_TIME_BASE_MAX_DAY_PLAN_EVENTS
  } };

/* --- globalConfiguration  ----------------------------------------------------- */
static snmp_err_t globalmoduletable_get_instance(const u32_t *column,
                                                 const u32_t *row_oid,
                                                 u8_t row_oid_len,
                                                 struct snmp_node_instance *
                                                 cell_instance)
{
  u8_t i;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid, row_oid_len, global_module_table_oid_ranges,
                         LWIP_ARRAYSIZE(global_module_table_oid_ranges)))
  {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif index from incoming OID */
  i = row_oid[0];

  /* find netif with index */
  if (i <= LWIP_ARRAYSIZE(GetSGlobalConfigurationPtr()->SaModules))
  {
    cell_instance->reference.u32 = (u32_t) (i);

    return SNMP_ERR_NOERROR;
  }

  return SNMP_ERR_NOSUCHINSTANCE;
}

static snmp_err_t globalmoduletable_get_next_instance(const u32_t *column,
                                                      struct snmp_obj_id *
                                                      row_oid,
                                                      struct snmp_node_instance
                                                      *cell_instance)
{
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(global_module_table_oid_ranges)];
  size_t i;

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state,
                     row_oid->id,
                     row_oid->len,
                     result_temp,
                     LWIP_ARRAYSIZE(global_module_table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  for (i = 1; i <= LWIP_ARRAYSIZE(GetSGlobalConfigurationPtr()->SaModules); i++)
  {
    u32_t test_oid[LWIP_ARRAYSIZE(global_module_table_oid_ranges)];

    test_oid[0] = i;

    /* check generated OID: is it a candidate for the next one? */
    snmp_next_oid_check(&state,
                        test_oid,
                        LWIP_ARRAYSIZE(global_module_table_oid_ranges),
                        (void *) i);
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS)
  {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    cell_instance->reference.u32 = LWIP_CONST_CAST(u32_t, state.reference);

    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}

static s16_t globalmoduletable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value)
{
  s16_t value_len;
  u32_t i = cell_instance->reference.u32 - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 1:
      {
        /* moduleNumber */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalConfigurationPtr()->SaModules[i].bNumber;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* moduleDeviceNode */
        value_len =
          sizeof(GetSGlobalConfigurationPtr()->SaModules[i].laDeviceNode);
        if ((value_len <= SNMP_MAX_VALUE_SIZE))
        {
          memcpy(value,
                 GetSGlobalConfigurationPtr()->SaModules[i].laDeviceNode,
                 value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      case 3:
      {
        /* moduleMake */
        value_len = strlen(GetSGlobalConfigurationPtr()->SaModules[i].strMake);
        if ((value_len <= SNMP_MAX_VALUE_SIZE))
        {
          memcpy(value,
                 GetSGlobalConfigurationPtr()->SaModules[i].strMake,
                 value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      case 4:
      {
        /* moduleModel */
        value_len = strlen(GetSGlobalConfigurationPtr()->SaModules[i].strModel);
        if ((value_len <= SNMP_MAX_VALUE_SIZE))
        {
          memcpy(value,
                 GetSGlobalConfigurationPtr()->SaModules[i].strModel,
                 value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      case 5:
      {
        /* moduleVersion */
        value_len =
          strlen(GetSGlobalConfigurationPtr()->SaModules[i].strVersion);
        if ((value_len <= SNMP_MAX_VALUE_SIZE))
        {
          memcpy(value,
                 GetSGlobalConfigurationPtr()->SaModules[i].strVersion,
                 value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      case 6:
      {
        /* moduleType */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalConfigurationPtr()->SaModules[i].bType;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("globalmoduletable_get_value(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* globalmoduletable_get_value */

static s16_t globalconfiguration_root_get_value(
  struct snmp_node_instance *instance,
  void *value)
{
  s16_t value_len;

  switch (instance->node->oid)
  {
      case 1:
      {
        /* globalSetIDParameter */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalConfigurationPtr()->sSetIDParameter;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* globalMaxModules */
        s32_t *v = (s32_t *) value;

        *v = GLOBAL_CONFIG_MAX_MODULES;
        value_len = sizeof(s32_t);
        break;
      }

      case 4:
      {
        /* controllerBaseStandards */
        value_len =
          strlen(GetSGlobalConfigurationPtr()->strControllerBaseStandards);
        if ((value_len <= SNMP_MAX_VALUE_SIZE))
        {
          memcpy(value,
                 GetSGlobalConfigurationPtr()->strControllerBaseStandards,
                 value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("globalconfiguration_root_get_value(): unknown id: %"S32_F
                     "\n", instance->node->oid));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* globalconfiguration_root_get_value */

/* --- globalDBManagement  ----------------------------------------------------- */
static s16_t globaldbmanagement_root_get_value(
  struct snmp_node_instance *instance,
  void *value)
{
  s16_t value_len;

  switch (instance->node->oid)
  {
      case 1:
      {
        /* dbCreateTransaction */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalDbManagementPtr()->bCreateTransaction;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* dbErrorType */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalDbManagementPtr()->bErrorType;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* dbErrorID */
        value_len = sizeof(GetSGlobalDbManagementPtr()->baErrorID);
        if (value_len <= SNMP_MAX_VALUE_SIZE)
        {
          memcpy(value, GetSGlobalDbManagementPtr()->baErrorID, value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      case 4:
      {
        /* dbTransactionID */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalDbManagementPtr()->bTransactionID;
        value_len = sizeof(s32_t);
        break;
      }

      case 5:
      {
        /* dbMakeID */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalDbManagementPtr()->bMakeID;
        value_len = sizeof(s32_t);
        break;
      }

      case 6:
      {
        /* dbVerifyStatus */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalDbManagementPtr()->bVerifyStatus;
        /* TODO: put requested value to '*v' here */
        value_len = sizeof(s32_t);
        LWIP_UNUSED_ARG(v);
        break;
      }

      case 7:
      {
        /* dbVerifyError */
        value_len = strlen(GetSGlobalDbManagementPtr()->strVerifyError);
        if (value_len <= SNMP_MAX_VALUE_SIZE)
        {
          memcpy(value,
                 GetSGlobalDbManagementPtr()->strVerifyError,
                 value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("globaldbmanagement_root_get_value(): unknown id: %"S32_F
                     "\n", instance->node->oid));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* globaldbmanagement_root_get_value */

static snmp_err_t globaldbmanagement_root_set_test(
  struct snmp_node_instance *instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_WRONGVALUE;

  switch (instance->node->oid)
  {
      case 1:
      {
        /* dbCreateTransaction */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 1) && (*v <= 3)) || (*v == 6))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 4:
      {
        /* dbTransactionID */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("globaldbmanagement_root_set_test(): unknown id: %"S32_F
                     "\n", instance->node->oid));
        break;
      }
  }

  return err;
} /* globaldbmanagement_root_set_test */

static snmp_err_t globaldbmanagement_root_set_value(
  struct snmp_node_instance *instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_NOERROR;

  LWIP_UNUSED_ARG(len);
  switch (instance->node->oid)
  {
      case 1:
      {
        /* dbCreateTransaction */
        s32_t *v = (s32_t *) value;

        GetSGlobalDbManagementPtr()->bCreateTransaction = *v;
        break;
      }

      case 4:
      {
        /* dbTransactionID */
        s32_t *v = (s32_t *) value;

        GetSGlobalDbManagementPtr()->bTransactionID = *v;
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("globaldbmanagement_root_set_value(): unknown id: %"S32_F
                     "\n", instance->node->oid));
        break;
      }
  }

  return err;
}

/* --- timebase 1,3,6,1,4,1,1206,4,2,6.3.3 ----------------------------------------------------- */
static snmp_err_t timebasescheduletable_get_instance(const u32_t *column,
                                                     const u32_t *row_oid,
                                                     u8_t row_oid_len,
                                                     struct snmp_node_instance *
                                                     cell_instance)
{
  u8_t i;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid,
                         row_oid_len,
                         time_base_schedule_table_oid_ranges,
                         LWIP_ARRAYSIZE(time_base_schedule_table_oid_ranges)))
  {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif index from incoming OID */
  i = row_oid[0];

  /* find netif with index */
  if (i <= LWIP_ARRAYSIZE(GetSGlobalTimeManagementPtr()->STimebase.SaSchedules))
  {
    cell_instance->reference.u32 = (u32_t) (i);

    return SNMP_ERR_NOERROR;
  }

  return SNMP_ERR_NOSUCHINSTANCE;
}

static snmp_err_t timebasescheduletable_get_next_instance(const u32_t *column,
                                                          struct snmp_obj_id *
                                                          row_oid,
                                                          struct
                                                          snmp_node_instance *
                                                          cell_instance)
{
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(time_base_schedule_table_oid_ranges)];
  size_t i;

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp,
                     LWIP_ARRAYSIZE(time_base_schedule_table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  for (i = 1;
       i
       <= LWIP_ARRAYSIZE(GetSGlobalTimeManagementPtr()->STimebase.SaSchedules);
       i++)
  {
    u32_t test_oid[LWIP_ARRAYSIZE(time_base_schedule_table_oid_ranges)];

    test_oid[0] = i;

    /* check generated OID: is it a candidate for the next one? */
    snmp_next_oid_check(&state, test_oid,
                        LWIP_ARRAYSIZE(time_base_schedule_table_oid_ranges),
                        (void *) i);
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS)
  {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    cell_instance->reference.u32 = LWIP_CONST_CAST(u32_t, state.reference);

    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}

static s16_t timebasescheduletable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value)
{
  s16_t value_len;

  u32_t i = cell_instance->reference.u32 - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 1:
      {
        /* timeBaseScheduleNumber */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->STimebase.SaSchedules[i].bNumber;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* timeBaseScheduleMonth */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->STimebase.SaSchedules[i].sMonth;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* timeBaseScheduleDay */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->STimebase.SaSchedules[i].bDay;
        value_len = sizeof(s32_t);
        break;
      }

      case 4:
      {
        /* timeBaseScheduleDate */
        u32_t *v = (u32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->STimebase.SaSchedules[i].lDate;
        value_len = sizeof(u32_t);
        break;
      }

      case 5:
      {
        /* timeBaseScheduleDayPlan */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->STimebase.SaSchedules[i].bDayPlan;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("timebasescheduletable_get_value(): unknown id: %"S32_F
                     "\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* timebasescheduletable_get_value */

static snmp_err_t timebasescheduletable_set_test(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_WRONGVALUE;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 2:
      {
        /* timeBaseScheduleMonth */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 65535)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 3:
      {
        /* timeBaseScheduleDay */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 4:
      {
        /* timeBaseScheduleDate */
        err = SNMP_ERR_NOERROR;
        break;
      }

      case 5:
      {
        /* timeBaseScheduleDayPlan */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("timebasescheduletable_set_test(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        break;
      }
  } /* switch */

  return err;
} /* timebasescheduletable_set_test */

static snmp_err_t timebasescheduletable_set_value(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_NOERROR;

  u32_t i = cell_instance->reference.u32 - 1;

  LWIP_UNUSED_ARG(len);
  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 2:
      {
        /* timeBaseScheduleMonth */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->STimebase.SaSchedules[i].sMonth = *v;
        break;
      }

      case 3:
      {
        /* timeBaseScheduleDay */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->STimebase.SaSchedules[i].bDay = *v;
        break;
      }

      case 4:
      {
        /* timeBaseScheduleDate */
        u32_t *v = (u32_t *) value;

        GetSGlobalTimeManagementPtr()->STimebase.SaSchedules[i].lDate = *v;
        break;
      }

      case 5:
      {
        /* timeBaseScheduleDayPlan */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->STimebase.SaSchedules[i].bDayPlan = *v;
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("timebasescheduletable_set_value(): unknown id: %"S32_F
                     "\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        break;
      }
  } /* switch */

  return err;
} /* timebasescheduletable_set_value */

static snmp_err_t timebasedayplantable_get_instance(const u32_t *column,
                                                    const u32_t *row_oid,
                                                    u8_t row_oid_len,
                                                    struct snmp_node_instance *
                                                    cell_instance)
{
  u8_t i, j;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid,
                         row_oid_len,
                         time_base_day_plan_table_oid_ranges,
                         LWIP_ARRAYSIZE(time_base_day_plan_table_oid_ranges)))
  {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  i = row_oid[0];
  j = row_oid[1];

  if (i <= LWIP_ARRAYSIZE(GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans))
  {
    if (j
        <= LWIP_ARRAYSIZE(
          GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i]))
    {
      return SNMP_ERR_NOERROR;
    }
  }

  return SNMP_ERR_NOSUCHINSTANCE;
}

static snmp_err_t timebasedayplantable_get_next_instance(const u32_t *column,
                                                         struct snmp_obj_id *
                                                         row_oid,
                                                         struct
                                                         snmp_node_instance *
                                                         cell_instance)
{
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(time_base_day_plan_table_oid_ranges)];
  u8_t i;
  u8_t j;

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp,
                     LWIP_ARRAYSIZE(time_base_day_plan_table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  for (i = 1;
       i
       <= LWIP_ARRAYSIZE(GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans);
       i++)
  {
    for (j = 1;
         j
         <= LWIP_ARRAYSIZE(
           GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i]);
         j++)
    {
      u32_t test_oid[LWIP_ARRAYSIZE(time_base_day_plan_table_oid_ranges)];

      test_oid[0] = i;
      test_oid[1] = j;
      snmp_next_oid_check(&state,
                          test_oid,
                          LWIP_ARRAYSIZE(time_base_day_plan_table_oid_ranges),
                          NULL);
    }
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS)
  {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);

    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}

static s16_t timebasedayplantable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value)
{
  s16_t value_len;
  u32_t *oid = cell_instance->instance_oid.id;
  u32_t i = oid[2] - 1;
  u32_t j = oid[3] - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 1:
      {
        /* dayPlanNumber */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i][j].bNumber;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* dayPlanEventNumber */
        s32_t *v = (s32_t *) value;

        *v =
          GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i][j].
          bEventNumber;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* dayPlanHour */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i][j].bHour;
        value_len = sizeof(s32_t);
        break;
      }

      case 4:
      {
        /* dayPlanMinute */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i][j].bMinute;
        value_len = sizeof(s32_t);
        break;
      }

      case 5:
      {
        /* dayPlanActionNumberOID */
        value_len =
          GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i][j].
          bActionNumberOIDLength;
        if (value_len <= SNMP_MAX_VALUE_SIZE)
        {
          memcpy(value,
                 GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i][j].
                 laActionNumberOID,
                 value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("timebasedayplantable_get_value(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* timebasedayplantable_get_value */

static snmp_err_t timebasedayplantable_set_test(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_WRONGVALUE;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 3:
      {
        /* dayPlanHour */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 23)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 4:
      {
        /* dayPlanMinute */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 59)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 5:
      {
        /* dayPlanActionNumberOID */
        err = SNMP_ERR_NOERROR;
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("timebasedayplantable_set_test(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        break;
      }
  } /* switch */

  return err;
} /* timebasedayplantable_set_test */

static snmp_err_t timebasedayplantable_set_value(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_NOERROR;
  u32_t *oid = cell_instance->instance_oid.id;
  u32_t i = oid[2] - 1;
  u32_t j = oid[3] - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 3:
      {
        /* dayPlanHour */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i][j].bHour = *v;
        break;
      }

      case 4:
      {
        /* dayPlanMinute */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i][j].bMinute = *v;
        break;
      }

      case 5:
      {
        /* dayPlanActionNumberOID */
        u32_t *v = (u32_t *) value;
        u8_t v_len = len;

        memset(
          GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i][j].
          laActionNumberOID,
          0,
          sizeof(GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i][j]
                 .laActionNumberOID));
        memcpy(
          GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i][j].
          laActionNumberOID,
          v,
          v_len);
        GetSGlobalTimeManagementPtr()->STimebase.SaaDayPlans[i][j].
        bActionNumberOIDLength = v_len;
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("timebasedayplantable_set_value(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        break;
      }
  }

  return err;
} /* timebasedayplantable_set_value */

static s16_t timebase_treenode_get_value(struct snmp_node_instance *instance,
                                         void *value)
{
  s16_t value_len;

  switch (instance->node->oid)
  {
      case 1:
      {
        /* maxTimebaseScheduleEntries */
        s32_t *v = (s32_t *) value;

        *v = GTM_TIME_BASE_MAX_SCHEDULES;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* maxDayPlans */
        s32_t *v = (s32_t *) value;

        *v = GTM_TIME_BASE_MAX_DAY_PLANS;
        value_len = sizeof(s32_t);
        break;
      }

      case 4:
      {
        /* maxDayPlanEvents */
        s32_t *v = (s32_t *) value;

        *v = GTM_TIME_BASE_MAX_DAY_PLAN_EVENTS;
        value_len = sizeof(s32_t);
        break;
      }

      case 6:
      {
        /* dayPlanStatus */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->STimebase.bDayPlanStatus;
        value_len = sizeof(s32_t);
        break;
      }

      case 7:
      {
        /* timeBaseScheduleTableStatus */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->STimebase.sScheduleTableStatus;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("timebase_treenode_get_value(): unknown id: %"S32_F"\n",
                     instance->node->oid));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* timebase_treenode_get_value */

/* --- daylightSavingNode 1,3,6,1,4,1,1206,4,2,6.3.7 ----------------------------------------------------- */
static s16_t maxDaylightSavingEntries_get_value(
  struct snmp_node_instance *instance,
  void *value)
{
  s16_t value_len;
  s32_t *v = (s32_t *) value;

  LWIP_UNUSED_ARG(instance);
  value_len = sizeof(s32_t);
  *v = GTM_DAYLIGHT_SAVINGS_MAX;

  return value_len;
}

static snmp_err_t dsttable_get_instance(const u32_t *column,
                                        const u32_t *row_oid,
                                        u8_t row_oid_len,
                                        struct snmp_node_instance *cell_instance)
{
  u8_t i;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid,
                         row_oid_len,
                         dst_table_oid_ranges,
                         LWIP_ARRAYSIZE(dst_table_oid_ranges)))
  {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif index from incoming OID */
  i = row_oid[0];

  /* find netif with index */
  if (i <= LWIP_ARRAYSIZE(GetSGlobalTimeManagementPtr()->SaDaylightSavings))
  {
    cell_instance->reference.u32 = (u32_t) (i);

    return SNMP_ERR_NOERROR;
  }

  return SNMP_ERR_NOSUCHINSTANCE;
}

static snmp_err_t dsttable_get_next_instance(const u32_t *column,
                                             struct snmp_obj_id *row_oid,
                                             struct snmp_node_instance *
                                             cell_instance)
{
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(dst_table_oid_ranges)];
  size_t i;

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state,
                     row_oid->id,
                     row_oid->len,
                     result_temp,
                     LWIP_ARRAYSIZE(dst_table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  for (i = 1;
       i <= LWIP_ARRAYSIZE(GetSGlobalTimeManagementPtr()->SaDaylightSavings);
       i++)
  {
    u32_t test_oid[LWIP_ARRAYSIZE(dst_table_oid_ranges)];

    test_oid[0] = i;

    /* check generated OID: is it a candidate for the next one? */
    snmp_next_oid_check(&state,
                        test_oid,
                        LWIP_ARRAYSIZE(dst_table_oid_ranges),
                        (void *) i);
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS)
  {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    cell_instance->reference.u32 = LWIP_CONST_CAST(u32_t, state.reference);

    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}

static s16_t dsttable_get_value(struct snmp_node_instance *cell_instance,
                                void *value)
{
  s16_t value_len;

  u32_t i = cell_instance->reference.u32 - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 1:
      {
        /* dstEntryNumber */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bNumber;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* dstBeginMonth */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bBeginMonth;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* dstBeginOccurrences */
        s32_t *v = (s32_t *) value;

        *v =
          GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bBeginOccurences;
        value_len = sizeof(s32_t);
        break;
      }

      case 4:
      {
        /* dstBeginDayOfWeek */
        s32_t *v = (s32_t *) value;

        *v =
          GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bBeginDayOfWeek;
        value_len = sizeof(s32_t);
        break;
      }

      case 5:
      {
        /* dstBeginDayOfMonth */
        s32_t *v = (s32_t *) value;

        *v =
          GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bBeginDayOfMonth;
        value_len = sizeof(s32_t);
        break;
      }

      case 6:
      {
        /* dstBeginSecondsToTransition */
        u32_t *v = (u32_t *) value;

        *v =
          GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].
          lBeginSecondToTransition;
        value_len = sizeof(u32_t);
        break;
      }

      case 7:
      {
        /* dstEndMonth */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bEndMonth;
        value_len = sizeof(s32_t);
        break;
      }

      case 8:
      {
        /* dstEndOccurrences */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bEndOccurences;
        value_len = sizeof(s32_t);
        break;
      }

      case 9:
      {
        /* dstEndDayOfWeek */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bEndDayOfWeek;
        value_len = sizeof(s32_t);
        break;
      }

      case 10:
      {
        /* dstEndDayOfMonth */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bEndDayOfMonth;
        value_len = sizeof(s32_t);
        break;
      }

      case 11:
      {
        /* dstEndSecondsToTransition */
        u32_t *v = (u32_t *) value;

        *v =
          GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].
          lEndSecondToTransition;
        value_len = sizeof(u32_t);
        break;
      }

      case 12:
      {
        /* dstSecondsToAdjust */
        s32_t *v = (s32_t *) value;

        *v =
          GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].sSecondsToAdjust;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("dsttable_get_value(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* dsttable_get_value */

static snmp_err_t dsttable_set_test(struct snmp_node_instance *cell_instance,
                                    u16_t len,
                                    void *value)
{
  snmp_err_t err = SNMP_ERR_WRONGVALUE;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 2:
      {
        /* dstBeginMonth */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 1) && (*v <= 15)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 3:
      {
        /* dstBeginOccurrences */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 1) && (*v <= 9)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 4:
      {
        /* dstBeginDayOfWeek */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 1) && (*v <= 7)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 5:
      {
        /* dstBeginDayOfMonth */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 1) && (*v <= 31)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 6:
      {
        /* dstBeginSecondsToTransition */
        err = SNMP_ERR_NOERROR;
        break;
      }

      case 7:
      {
        /* dstEndMonth */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 1) && (*v <= 12)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 8:
      {
        /* dstEndOccurrences */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 1) && (*v <= 9)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 9:
      {
        /* dstEndDayOfWeek */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 1) && (*v <= 7)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 10:
      {
        /* dstEndDayOfMonth */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 1) && (*v <= 31)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 11:
      {
        /* dstEndSecondsToTransition */
        err = SNMP_ERR_NOERROR;
        break;
      }

      case 12:
      {
        /* dstSecondsToAdjust */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 21600)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("dsttable_set_test(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        break;
      }
  } /* switch */

  return err;
} /* dsttable_set_test */

static snmp_err_t dsttable_set_value(struct snmp_node_instance *cell_instance,
                                     u16_t len,
                                     void *value)
{
  snmp_err_t err = SNMP_ERR_NOERROR;
  u32_t i = cell_instance->reference.u32 - 1;

  LWIP_UNUSED_ARG(len);
  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 2:
      {
        /* dstBeginMonth */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bBeginMonth = *v;
        break;
      }

      case 3:
      {
        /* dstBeginOccurrences */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bBeginOccurences =
          *v;
        break;
      }

      case 4:
      {
        /* dstBeginDayOfWeek */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bBeginDayOfWeek =
          *v;
        break;
      }

      case 5:
      {
        /* dstBeginDayOfMonth */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bBeginDayOfMonth =
          *v;
        break;
      }

      case 6:
      {
        /* dstBeginSecondsToTransition */
        u32_t *v = (u32_t *) value;

        GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].
        lBeginSecondToTransition = *v;
        break;
      }

      case 7:
      {
        /* dstEndMonth */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bEndMonth = *v;
        LWIP_UNUSED_ARG(v);
        break;
      }

      case 8:
      {
        /* dstEndOccurrences */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bEndOccurences = *v;
        LWIP_UNUSED_ARG(v);
        break;
      }

      case 9:
      {
        /* dstEndDayOfWeek */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bEndDayOfWeek = *v;
        break;
      }

      case 10:
      {
        /* dstEndDayOfMonth */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].bEndDayOfMonth = *v;
        break;
      }

      case 11:
      {
        /* dstEndSecondsToTransition */
        u32_t *v = (u32_t *) value;

        GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].
        lEndSecondToTransition = *v;
        break;
      }

      case 12:
      {
        /* dstSecondsToAdjust */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->SaDaylightSavings[i].sSecondsToAdjust =
          *v;
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("dsttable_set_value(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        break;
      }
  } /* switch */

  return err;
} /* dsttable_set_value */

/* --- globalTimeManagement  ----------------------------------------------------- */
static s16_t globaltimemanagement_root_get_value(
  struct snmp_node_instance *instance,
  void *value)
{
  s16_t value_len;

  switch (instance->node->oid)
  {
      case 1:
      {
        /* globalTime */
        u32_t *v = (u32_t *) value;

        GTMGetGlobalTime(v);
        PPPOSAsynchResetConnectionTimeout();
        value_len = sizeof(u32_t);
        break;
      }

      case 2:
      {
        /* globalDaylightSaving */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->bDaylightSaving;
        value_len = sizeof(s32_t);
        break;
      }

      case 4:
      {
        /* globalLocalTimeDifferential */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->lGlobalLocalTimeDifferential;
        value_len = sizeof(s32_t);
        break;
      }

      case 5:
      {
        /* controllerStandardTimeZone */
        s32_t *v = (s32_t *) value;

        *v = GetSGlobalTimeManagementPtr()->lControllerStandardTimeZone;
        value_len = sizeof(s32_t);
        break;
      }

      case 6:
      {
        /* controllerLocalTime */
        u32_t *v = (u32_t *) value;

        GTMGetControllerLocalTime(v);
        value_len = sizeof(u32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("globaltimemanagement_root_get_value(): unknown id: %"S32_F
                     "\n", instance->node->oid));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* globaltimemanagement_root_get_value */

static snmp_err_t globaltimemanagement_root_set_test(
  struct snmp_node_instance *instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_WRONGVALUE;

  switch (instance->node->oid)
  {
      case 1:
      {
        /* globalTime */
        err = SNMP_ERR_NOERROR;
        break;
      }

      case 2:
      {
        /* globalDaylightSaving */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 1) && (*v <= 19)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 4:
      {
        /* globalLocalTimeDifferential */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= -43200) && (*v <= 43200)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 5:
      {
        /* controllerStandardTimeZone */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= -43200) && (*v <= 43200)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("globaltimemanagement_root_set_test(): unknown id: %"S32_F
                     "\n", instance->node->oid));
        break;
      }
  } /* switch */

  return err;
} /* globaltimemanagement_root_set_test */

static snmp_err_t globaltimemanagement_root_set_value(
  struct snmp_node_instance *instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_NOERROR;

  LWIP_UNUSED_ARG(len);
  switch (instance->node->oid)
  {
      case 1:
      {
        /* globalTime */
        u32_t *v = (u32_t *) value;

        if (!GTMSetGlobalTime(*v))
        {
          err = SNMP_ERR_WRONGVALUE;
        }

        break;
      }

      case 2:
      {
        /* globalDaylightSaving */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->bDaylightSaving = *v;
        break;
      }

      case 4:
      {
        /* globalLocalTimeDifferential */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->lGlobalLocalTimeDifferential = *v;
        break;
      }

      case 5:
      {
        /* controllerStandardTimeZone */
        s32_t *v = (s32_t *) value;

        GetSGlobalTimeManagementPtr()->lControllerStandardTimeZone = *v;
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("globaltimemanagement_root_set_value(): unknown id: %"S32_F
                     "\n", instance->node->oid));
        break;
      }
  } /* switch */

  return err;
} /* globaltimemanagement_root_set_value */

#endif /* LWIP_SNMP */
