/*
 *  Generated by LwipMibCompiler
 */

#ifndef NTCIP_1202V0328_H
#define NTCIP_1202V0328_H NTCIP_1202V0328_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp_core.h"

extern const struct snmp_mib asc;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP */
#endif /* 1202V0328_H */
