/*
 *  Generated by LwipMibCompiler
 */

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#include "tc_kgm_v0.7.h"
#include "lwip/apps/snmp.h"
#include "lwip/apps/snmp_core.h"
#include "lwip/apps/snmp_scalar.h"
#include "lwip/apps/snmp_table.h"

#include  "data.h"
#include  <string.h>

/* --- kgmChannel 1.3.6.1.4.1.59873.4.2.1.2 ----------------------------------------------------- */
static s16_t kgmchannel_treenode_get_value(struct snmp_node_instance *instance,
                                           void *value);

static const struct snmp_scalar_node kgmmaxtrffclghtfltstatusgroups_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(1,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   kgmchannel_treenode_get_value);

static snmp_err_t kgmtrffclghtfltstatustable_get_instance(const u32_t *column,
                                                          const u32_t *row_oid,
                                                          u8_t row_oid_len,
                                                          struct
                                                          snmp_node_instance *
                                                          cell_instance);
static snmp_err_t kgmtrffclghtfltstatustable_get_next_instance(
  const u32_t *column,
  struct
  snmp_obj_id *
  row_oid,
  struct
  snmp_node_instance
  *cell_instance);
static s16_t kgmtrffclghtfltstatustable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value);

static const struct snmp_table_col_def kgmtrffclghtfltstatustable_columns[] =
{ { 1, SNMP_ASN1_TYPE_INTEGER,
    SNMP_NODE_INSTANCE_READ_ONLY },
  /* kgmTrffcLghtFltStatusNumber */
  {
    2, SNMP_ASN1_TYPE_INTEGER,
    SNMP_NODE_INSTANCE_READ_ONLY
  },
  /* kgmTrffcLghtFltGreenStatus */
  {
    3, SNMP_ASN1_TYPE_INTEGER,
    SNMP_NODE_INSTANCE_READ_ONLY
  },
  /* kgmTrffcLghtFltYellowStatus */
  {
    4, SNMP_ASN1_TYPE_INTEGER,
    SNMP_NODE_INSTANCE_READ_ONLY
  },
  /* kgmTrffcLghtFltRedStatus */
};
static const struct snmp_table_node kgmtrffclghtfltstatustable =
  SNMP_TABLE_CREATE(2,
                    kgmtrffclghtfltstatustable_columns,
                    kgmtrffclghtfltstatustable_get_instance,
                    kgmtrffclghtfltstatustable_get_next_instance,
                    kgmtrffclghtfltstatustable_get_value,
                    NULL,
                    NULL)
;

static const struct snmp_scalar_node kgmmaxchannelerrorflagsgroups_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(3,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   kgmchannel_treenode_get_value);

static snmp_err_t kgmchannelerrorflagstable_get_instance(const u32_t *column,
                                                         const u32_t *row_oid,
                                                         u8_t row_oid_len,
                                                         struct
                                                         snmp_node_instance *
                                                         cell_instance);
static snmp_err_t kgmchannelerrorflagstable_get_next_instance(
  const u32_t *column,
  struct snmp_obj_id
  *row_oid,
  struct
  snmp_node_instance
  *cell_instance);
static s16_t kgmchannelerrorflagstable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value);

static const struct snmp_table_col_def kgmchannelerrorflagstable_columns[] =
{ { 1, SNMP_ASN1_TYPE_INTEGER,
    SNMP_NODE_INSTANCE_READ_ONLY },
  /* kgmErrorFlagsGroupNumber */
  {
    2, SNMP_ASN1_TYPE_INTEGER,
    SNMP_NODE_INSTANCE_READ_ONLY
  },
  /* kgmRedLampAllFailure */
  {
    3, SNMP_ASN1_TYPE_INTEGER,
    SNMP_NODE_INSTANCE_READ_ONLY
  },
  /* kgmGreenLampAllFailure */
  {
    4, SNMP_ASN1_TYPE_INTEGER,
    SNMP_NODE_INSTANCE_READ_ONLY
  },
  /* kgmYellowLampAllFailure */
  {
    5, SNMP_ASN1_TYPE_INTEGER,
    SNMP_NODE_INSTANCE_READ_ONLY
  },
  /* kgmUndesiredRedSignal */
  {
    6, SNMP_ASN1_TYPE_INTEGER,
    SNMP_NODE_INSTANCE_READ_ONLY
  },
  /* kgmUndesiredGreenSignal */
  {
    7, SNMP_ASN1_TYPE_INTEGER,
    SNMP_NODE_INSTANCE_READ_ONLY
  },
  /* kgmUndesiredYellowSignal */
};
static const struct snmp_table_node kgmchannelerrorflagstable =
  SNMP_TABLE_CREATE(4,
                    kgmchannelerrorflagstable_columns,
                    kgmchannelerrorflagstable_get_instance,
                    kgmchannelerrorflagstable_get_next_instance,
                    kgmchannelerrorflagstable_get_value,
                    NULL,
                    NULL)
;

static const struct snmp_node *const kgmchannel_subnodes[] =
{ &kgmmaxtrffclghtfltstatusgroups_scalar.node.node,
  &
  kgmtrffclghtfltstatustable.node.node,
  &
  kgmmaxchannelerrorflagsgroups_scalar.node.node,
  &
  kgmchannelerrorflagstable.node.node };
static const struct snmp_tree_node kgmchannel_treenode =
  SNMP_CREATE_TREE_NODE(2,
                        kgmchannel_subnodes);

/* --- kgmSignalState 1.3.6.1.4.1.59873.4.2.1.3 ----------------------------------------------------- */
static s16_t kgmsignalstate_treenode_get_value(
  struct snmp_node_instance *instance,
  void *value);

static const struct snmp_scalar_node kgmmaxsignalstate_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(1,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   kgmsignalstate_treenode_get_value);

static snmp_err_t kgmsignalstatetable_get_instance(const u32_t *column,
                                                   const u32_t *row_oid,
                                                   u8_t row_oid_len,
                                                   struct snmp_node_instance *
                                                   cell_instance);
static snmp_err_t kgmsignalstatetable_get_next_instance(const u32_t *column,
                                                        struct snmp_obj_id *
                                                        row_oid,
                                                        struct
                                                        snmp_node_instance *
                                                        cell_instance);
static s16_t kgmsignalstatetable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value);

static const struct snmp_table_col_def kgmsignalstatetable_columns[] = { { 1,
                                                                           SNMP_ASN1_TYPE_INTEGER,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStateNumber */
                                                                         { 2,
                                                                           SNMP_ASN1_TYPE_INTEGER,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStatePatternNo */
                                                                         { 3,
                                                                           SNMP_ASN1_TYPE_INTEGER,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStateExecMode */
                                                                         { 4,
                                                                           SNMP_ASN1_TYPE_INTEGER,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStatePlanMode */
                                                                         { 5,
                                                                           SNMP_ASN1_TYPE_INTEGER,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStateStructure */
                                                                         { 6,
                                                                           SNMP_ASN1_TYPE_INTEGER,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStatePlan */
                                                                         { 7,
                                                                           SNMP_ASN1_TYPE_OCTET_STRING,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStatePhase */
                                                                         { 8,
                                                                           SNMP_ASN1_TYPE_OCTET_STRING,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStateNextPhase */
                                                                         { 9,
                                                                           SNMP_ASN1_TYPE_INTEGER,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStateStep */
                                                                         { 10,
                                                                           SNMP_ASN1_TYPE_INTEGER,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStateTransitionFlag */
                                                                         { 11,
                                                                           SNMP_ASN1_TYPE_INTEGER,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStateTransitionStep */
                                                                         { 12,
                                                                           SNMP_ASN1_TYPE_OCTET_STRING,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStateElapsedTime */
                                                                         { 13,
                                                                           SNMP_ASN1_TYPE_OCTET_STRING,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStateRemainingTime */
                                                                         { 14,
                                                                           SNMP_ASN1_TYPE_INTEGER,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStateStepTime */
                                                                         { 15,
                                                                           SNMP_ASN1_TYPE_INTEGER,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmSignalStateCycleTime */
                                                                         { 16,
                                                                           SNMP_ASN1_TYPE_INTEGER,
                                                                           SNMP_NODE_INSTANCE_READ_ONLY },
                                                                         /* kgmTrPatternTimeToNextCycle */
};
static const struct snmp_table_node kgmsignalstatetable =
  SNMP_TABLE_CREATE(2,
                    kgmsignalstatetable_columns,
                    kgmsignalstatetable_get_instance,
                    kgmsignalstatetable_get_next_instance,
                    kgmsignalstatetable_get_value,
                    NULL,
                    NULL)
;

static const struct snmp_scalar_node kgmsignalplanlastchangetimes_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(3,
                                   SNMP_ASN1_TYPE_COUNTER,
                                   kgmsignalstate_treenode_get_value);

static const struct snmp_node *const kgmsignalstate_subnodes[] =
{ &kgmmaxsignalstate_scalar.node.node,
  &
  kgmsignalstatetable.node.node,
  &
  kgmsignalplanlastchangetimes_scalar.node.node };
static const struct snmp_tree_node kgmsignalstate_treenode =
  SNMP_CREATE_TREE_NODE(3, kgmsignalstate_subnodes);

/* --- kgmTrPattern 4294967295.59873.4.2.1.4 ----------------------------------------------------- */
static s16_t kgmtrpattern_treenode_get_value(
  struct snmp_node_instance *instance,
  void *value);
static snmp_err_t kgmtrpattern_treenode_set_test(
  struct snmp_node_instance *instance,
  u16_t len,
  void *value);
static snmp_err_t kgmtrpattern_treenode_set_value(
  struct snmp_node_instance *instance,
  u16_t len,
  void *value);

static const struct snmp_scalar_node kgmmaxsubjunctions_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(1,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   kgmtrpattern_treenode_get_value);

static const struct snmp_scalar_node kgmmaxtrpatterns_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(2,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   kgmtrpattern_treenode_get_value);

static snmp_err_t kgmtrpatterntable_get_instance(const u32_t *column,
                                                 const u32_t *row_oid,
                                                 u8_t row_oid_len,
                                                 struct snmp_node_instance *
                                                 cell_instance);
static snmp_err_t kgmtrpatterntable_get_next_instance(const u32_t *column,
                                                      struct snmp_obj_id *
                                                      row_oid,
                                                      struct snmp_node_instance
                                                      *cell_instance);
static s16_t kgmtrpatterntable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value);
static snmp_err_t kgmtrpatterntable_set_test(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value);
static snmp_err_t kgmtrpatterntable_set_value(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value);

static const struct snmp_table_col_def kgmtrpatterntable_columns[] = { { 1,
                                                                         SNMP_ASN1_TYPE_INTEGER,
                                                                         SNMP_NODE_INSTANCE_READ_ONLY },
                                                                       /* kgmSubjunctionNumber */
                                                                       { 2,
                                                                         SNMP_ASN1_TYPE_INTEGER,
                                                                         SNMP_NODE_INSTANCE_READ_ONLY },
                                                                       /* kgmTrPatternNumber */
                                                                       { 3,
                                                                         SNMP_ASN1_TYPE_INTEGER,
                                                                         SNMP_NODE_INSTANCE_READ_ONLY },
                                                                       /* kgmTrPatternPriority */
                                                                       { 4,
                                                                         SNMP_ASN1_TYPE_INTEGER,
                                                                         SNMP_NODE_INSTANCE_READ_WRITE },
                                                                       /* kgmTrPatternPlanMode */
                                                                       { 5,
                                                                         SNMP_ASN1_TYPE_INTEGER,
                                                                         SNMP_NODE_INSTANCE_READ_ONLY },
                                                                       /* kgmTrPatternExtendedMode */
                                                                       { 6,
                                                                         SNMP_ASN1_TYPE_INTEGER,
                                                                         SNMP_NODE_INSTANCE_READ_ONLY },
                                                                       /* kgmTrPatternSequenceNumber */
                                                                       { 7,
                                                                         SNMP_ASN1_TYPE_INTEGER,
                                                                         SNMP_NODE_INSTANCE_READ_WRITE },
                                                                       /* kgmTrPatternSplitNumber */
                                                                       { 8,
                                                                         SNMP_ASN1_TYPE_INTEGER,
                                                                         SNMP_NODE_INSTANCE_READ_WRITE },
                                                                       /* kgmTrPatternCoordStatus */
                                                                       { 9,
                                                                         SNMP_ASN1_TYPE_INTEGER,
                                                                         SNMP_NODE_INSTANCE_READ_WRITE },
                                                                       /* kgmTrPatternOutputSupervision */
                                                                       { 10,
                                                                         SNMP_ASN1_TYPE_OBJECT_ID,
                                                                         SNMP_NODE_INSTANCE_READ_WRITE },
                                                                       /* kgmTrPatternSpecParamTableOID */
};
static const struct snmp_table_node kgmtrpatterntable =
  SNMP_TABLE_CREATE(3,
                    kgmtrpatterntable_columns,
                    kgmtrpatterntable_get_instance,
                    kgmtrpatterntable_get_next_instance,
                    kgmtrpatterntable_get_value,
                    kgmtrpatterntable_set_test,
                    kgmtrpatterntable_set_value)
;

static const struct snmp_scalar_node kgmmaxtrcoords_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(4,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   kgmtrpattern_treenode_get_value);

static snmp_err_t kgmtrcoordtable_get_instance(const u32_t *column,
                                               const u32_t *row_oid,
                                               u8_t row_oid_len,
                                               struct snmp_node_instance *
                                               cell_instance);
static snmp_err_t kgmtrcoordtable_get_next_instance(const u32_t *column,
                                                    struct snmp_obj_id *row_oid,
                                                    struct snmp_node_instance *
                                                    cell_instance);
static s16_t kgmtrcoordtable_get_value(struct snmp_node_instance *cell_instance,
                                       void *value);
static snmp_err_t kgmtrcoordtable_set_test(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value);
static snmp_err_t kgmtrcoordtable_set_value(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value);

static const struct snmp_table_col_def kgmtrcoordtable_columns[] = { { 1,
                                                                       SNMP_ASN1_TYPE_INTEGER,
                                                                       SNMP_NODE_INSTANCE_READ_ONLY },
                                                                     /* kgmTrCoordNumber */
                                                                     { 2,
                                                                       SNMP_ASN1_TYPE_INTEGER,
                                                                       SNMP_NODE_INSTANCE_READ_WRITE },
                                                                     /* kgmTrCoordCycleTime */
                                                                     { 3,
                                                                       SNMP_ASN1_TYPE_INTEGER,
                                                                       SNMP_NODE_INSTANCE_READ_WRITE },
                                                                     /* kgmTrCoordGeneralOffsetTime */
                                                                     { 4,
                                                                       SNMP_ASN1_TYPE_INTEGER,
                                                                       SNMP_NODE_INSTANCE_READ_WRITE },
                                                                     /* kgmTrCoordPhaseId01 */
                                                                     { 5,
                                                                       SNMP_ASN1_TYPE_INTEGER,
                                                                       SNMP_NODE_INSTANCE_READ_WRITE },
                                                                     /* kgmTrCoordPhase01minDuration */
                                                                     { 6,
                                                                       SNMP_ASN1_TYPE_INTEGER,
                                                                       SNMP_NODE_INSTANCE_READ_WRITE },
                                                                     /* kgmTrCoordOffset01 */
                                                                     { 7,
                                                                       SNMP_ASN1_TYPE_INTEGER,
                                                                       SNMP_NODE_INSTANCE_READ_WRITE },
                                                                     /* kgmTrCoordReturnPhaseId01 */
                                                                     { 8,
                                                                       SNMP_ASN1_TYPE_INTEGER,
                                                                       SNMP_NODE_INSTANCE_READ_WRITE },
                                                                     /* kgmTrCoordPhaseId02 */
                                                                     { 9,
                                                                       SNMP_ASN1_TYPE_INTEGER,
                                                                       SNMP_NODE_INSTANCE_READ_WRITE },
                                                                     /* kgmTrCoordPhase02minDuration */
                                                                     { 10,
                                                                       SNMP_ASN1_TYPE_INTEGER,
                                                                       SNMP_NODE_INSTANCE_READ_WRITE },
                                                                     /* kgmTrCoordOffset02 */
                                                                     { 11,
                                                                       SNMP_ASN1_TYPE_INTEGER,
                                                                       SNMP_NODE_INSTANCE_READ_WRITE },
                                                                     /* kgmTrCoordReturnPhaseId02 */
};
static const struct snmp_table_node kgmtrcoordtable =
  SNMP_TABLE_CREATE(5,
                    kgmtrcoordtable_columns,
                    kgmtrcoordtable_get_instance,
                    kgmtrcoordtable_get_next_instance,
                    kgmtrcoordtable_get_value,
                    kgmtrcoordtable_set_test,
                    kgmtrcoordtable_set_value)
;

static const struct snmp_scalar_node kgmsignalplanupgrade_scalar =
  SNMP_SCALAR_CREATE_NODE(6,
                          SNMP_NODE_INSTANCE_READ_WRITE,
                          SNMP_ASN1_TYPE_INTEGER,
                          kgmtrpattern_treenode_get_value,
                          kgmtrpattern_treenode_set_test,
                          kgmtrpattern_treenode_set_value)
;

static const struct snmp_node *const kgmtrpattern_subnodes[] =
{ &kgmmaxsubjunctions_scalar.node.node,
  &
  kgmmaxtrpatterns_scalar.node.node, &kgmtrpatterntable
  .node.node,
  &
  kgmmaxtrcoords_scalar.node.node, &kgmtrcoordtable.node
  .node,
  &
  kgmsignalplanupgrade_scalar.node.node };
static const struct snmp_tree_node kgmtrpattern_treenode =
  SNMP_CREATE_TREE_NODE(4, kgmtrpattern_subnodes);

/* --- kgmUser 1.3.6.1.4.1.59873.4.2.1.6 ----------------------------------------------------- */
static s16_t kgmuser_treenode_get_value(struct snmp_node_instance *instance,
                                        void *value);

static const struct snmp_scalar_node kgmmaxuseroperations_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(1,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   kgmuser_treenode_get_value);

static snmp_err_t kgmuseroperationstable_get_instance(const u32_t *column,
                                                      const u32_t *row_oid,
                                                      u8_t row_oid_len,
                                                      struct snmp_node_instance
                                                      *cell_instance);
static snmp_err_t kgmuseroperationstable_get_next_instance(const u32_t *column,
                                                           struct snmp_obj_id *
                                                           row_oid,
                                                           struct
                                                           snmp_node_instance *
                                                           cell_instance);
static s16_t kgmuseroperationstable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value);

static const struct snmp_table_col_def kgmuseroperationstable_columns[] = { { 1,
                                                                              SNMP_ASN1_TYPE_INTEGER,
                                                                              SNMP_NODE_INSTANCE_READ_ONLY },
                                                                            /* kgmUserOperationsNumber */
                                                                            { 2,
                                                                              SNMP_ASN1_TYPE_INTEGER,
                                                                              SNMP_NODE_INSTANCE_READ_ONLY },
                                                                            /* kgmUserOperationsType */
                                                                            { 3,
                                                                              SNMP_ASN1_TYPE_COUNTER,
                                                                              SNMP_NODE_INSTANCE_READ_ONLY },
                                                                            /* kgmUserOperationsTimes */
                                                                            { 4,
                                                                              SNMP_ASN1_TYPE_OCTET_STRING,
                                                                              SNMP_NODE_INSTANCE_READ_ONLY },
                                                                            /* kgmUserOperationsULoginName */
};
static const struct snmp_table_node kgmuseroperationstable =
  SNMP_TABLE_CREATE(2,
                    kgmuseroperationstable_columns,
                    kgmuseroperationstable_get_instance,
                    kgmuseroperationstable_get_next_instance,
                    kgmuseroperationstable_get_value,
                    NULL,
                    NULL)
;

static const struct snmp_scalar_node kgmuserlistfileupdate_scalar =
  SNMP_SCALAR_CREATE_NODE_READONLY(3,
                                   SNMP_ASN1_TYPE_INTEGER,
                                   kgmuser_treenode_get_value);

static const struct snmp_node *const kgmuser_subnodes[] =
{ &kgmmaxuseroperations_scalar.node.node,
  &
  kgmuseroperationstable.node.node,
  &
  kgmuserlistfileupdate_scalar.node.node };
static const struct snmp_tree_node kgmuser_treenode = SNMP_CREATE_TREE_NODE(6,
                                                                            kgmuser_subnodes);

/* --- kgmAsc 1.3.6.1.4.1.59873.4.2.1 ----------------------------------------------------- */
static s16_t kgmmoduleerrorstatus_scalars_get_value(
  const struct snmp_scalar_array_node_def *node,
  void *value);

static const struct snmp_scalar_array_node_def
  kgmmoduleerrorstatus_scalars_nodes[] = {
  { 1, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY },   /* kgmMaxDriverModuleGroupStatus */
  { 2, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY },   /* kgmDriverModuleGroupStatus */
};
static const struct snmp_scalar_array_node kgmmoduleerrorstatus_scalars =
  SNMP_SCALAR_CREATE_ARRAY_NODE(1,
                                kgmmoduleerrorstatus_scalars_nodes,
                                kgmmoduleerrorstatus_scalars_get_value,
                                NULL,
                                NULL)
;

static s16_t kgmdetector_scalars_get_value(
  const struct snmp_scalar_array_node_def *node,
  void *value);

static const struct snmp_scalar_array_node_def kgmdetector_scalars_nodes[] =
{ { 1, SNMP_ASN1_TYPE_INTEGER,
    SNMP_NODE_INSTANCE_READ_ONLY },
  /* kgmDedectorModuleStatus */
};
static const struct snmp_scalar_array_node kgmdetector_scalars =
  SNMP_SCALAR_CREATE_ARRAY_NODE(5,
                                kgmdetector_scalars_nodes,
                                kgmdetector_scalars_get_value,
                                NULL,
                                NULL);

static const struct snmp_node *const kgmasc_subnodes[] =
{ &kgmmoduleerrorstatus_scalars.node.node, &kgmchannel_treenode
  .node,
  &
  kgmsignalstate_treenode.node, &kgmtrpattern_treenode.node,
  &kgmdetector_scalars.
  node.node, &kgmuser_treenode.node };
static const struct snmp_tree_node kgmasc_treenode = SNMP_CREATE_TREE_NODE(1,
                                                                           kgmasc_subnodes);

/* --- kgmDevices 1.3.6.1.4.1.59873.4.2 ----------------------------------------------------- */
static const struct snmp_node *const kgmdevices_subnodes[] =
{ &kgmasc_treenode.node };
static const struct snmp_tree_node kgmdevices_treenode =
  SNMP_CREATE_TREE_NODE(2,
                        kgmdevices_subnodes);

/* --- kgmTransportation 1.3.6.1.4.1.59873.4 ----------------------------------------------------- */
static const struct snmp_node *const kgmtransportation_subnodes[] =
{ &kgmdevices_treenode.node };
static const struct snmp_tree_node kgmtransportation_treenode =
  SNMP_CREATE_TREE_NODE(4, kgmtransportation_subnodes);

/* --- kgm  ----------------------------------------------------- */
static const struct snmp_node *const kgm_subnodes[] =
{ &kgmtransportation_treenode.node };
static const struct snmp_tree_node kgm_root = SNMP_CREATE_TREE_NODE(59873,
                                                                    kgm_subnodes);
static const u32_t kgm_base_oid[] = { 1, 3, 6, 1, 4, 1, 59873 };
const struct snmp_mib kgm = { kgm_base_oid, LWIP_ARRAYSIZE(kgm_base_oid),
                              &kgm_root.node };

/*
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 +  LWIP MIB generator - preserved section begin
 +  Code below is preserved on regeneration. Remove these comment lines to regenerate code.
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 */
static const struct snmp_oid_range user_operations_table_oid_ranges[] = { { 1,
                                                                            USER_OPERATIONS_MAX } };

static const struct snmp_oid_range signal_state_table_oid_ranges[] = { { 1,
                                                                         SIGNAL_STATES_MAX } };

static const struct snmp_oid_range traffic_light_fault_status_table_oid_ranges[]
  = { { 1, SIGNAL_GROUPS_MAX } };

static const struct snmp_oid_range channel_erro_flags_table_oid_ranges[] =
{ { 1, CHANNEL_ERROR_FLAGS_MAX } };

static const struct snmp_oid_range tr_pattern_table_oid_ranges[] = { { 1,
                                                                       TR_PATTERNS_SUBJUNCTIONS_MAX },
                                                                     {
                                                                       1,
                                                                       TR_PATERNS_MAX
                                                                     } };

static const struct snmp_oid_range tr_coord_table_oid_ranges[] = { { 1,
                                                                     TR_COORDS_MAX } };

/* --- kgmChannel 1.3.6.1.4.1.59873.4.2.1.2 ----------------------------------------------------- */
static snmp_err_t kgmtrffclghtfltstatustable_get_instance(const u32_t *column,
                                                          const u32_t *row_oid,
                                                          u8_t row_oid_len,
                                                          struct
                                                          snmp_node_instance *
                                                          cell_instance)
{
  u8_t i;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid,
                         row_oid_len,
                         traffic_light_fault_status_table_oid_ranges,
                         LWIP_ARRAYSIZE(
                           traffic_light_fault_status_table_oid_ranges)))
  {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif index from incoming OID */
  i = row_oid[0];

  /* find netif with index */
  if (i <= LWIP_ARRAYSIZE(GetSRuntimePtr()->SaSGRuntimes))
  {
    cell_instance->reference.u32 = (u32_t) (i);

    return SNMP_ERR_NOERROR;
  }

  return SNMP_ERR_NOSUCHINSTANCE;
}

static snmp_err_t kgmtrffclghtfltstatustable_get_next_instance(
  const u32_t *column,
  struct snmp_obj_id *row_oid,
  struct
  snmp_node_instance *cell_instance)
{
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(
                      traffic_light_fault_status_table_oid_ranges)];
  size_t i;

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp,
                     LWIP_ARRAYSIZE(
                       traffic_light_fault_status_table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  for (i = 1; i <= LWIP_ARRAYSIZE(GetSRuntimePtr()->SaSGRuntimes); i++)
  {
    u32_t test_oid[LWIP_ARRAYSIZE(traffic_light_fault_status_table_oid_ranges)];

    test_oid[0] = i;

    /* check generated OID: is it a candidate for the next one? */
    snmp_next_oid_check(&state,
                        test_oid,
                        LWIP_ARRAYSIZE(
                          traffic_light_fault_status_table_oid_ranges),
                        (void *) i);
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS)
  {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    cell_instance->reference.u32 = LWIP_CONST_CAST(u32_t, state.reference);

    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}

static s16_t kgmtrffclghtfltstatustable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value)
{
  s16_t value_len;
  u32_t i = cell_instance->reference.u32 - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 1:
      {
        /* kgmTrafficLightFaultIndex */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSGRuntimes[i].bIdx;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* kgmTrffcLghtFltGreenStatus */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSGRuntimes[i].USOGreenFaults.bSOGreenFaults;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* kgmTrffcLghtFltYellowStatus */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSGRuntimes[i].USOYellowFaults.bSOYellowFaults;
        value_len = sizeof(s32_t);
        break;
      }

      case 4:
      {
        /* kgmTrffcLghtFltRedStatus */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSGRuntimes[i].USORedFaults.bSORedFaults;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    (
                      "kgmtrffclghtfltstatustable_get_value(): unknown id: %"S32_F
                      "\n",
                      SNMP_TABLE_GET_COLUMN_FROM_OID(
                        cell_instance->instance_oid.id)));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* kgmtrffclghtfltstatustable_get_value */

static snmp_err_t kgmchannelerrorflagstable_get_instance(const u32_t *column,
                                                         const u32_t *row_oid,
                                                         u8_t row_oid_len,
                                                         struct
                                                         snmp_node_instance *
                                                         cell_instance)
{
  u8_t i;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid,
                         row_oid_len,
                         channel_erro_flags_table_oid_ranges,
                         LWIP_ARRAYSIZE(channel_erro_flags_table_oid_ranges)))
  {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif index from incoming OID */
  i = row_oid[0];

  /* find netif with index */
  if (i <= LWIP_ARRAYSIZE(GetSRuntimePtr()->SaChannelErrors))
  {
    cell_instance->reference.u32 = (u32_t) (i);

    return SNMP_ERR_NOERROR;
  }

  return SNMP_ERR_NOSUCHINSTANCE;
}

static snmp_err_t kgmchannelerrorflagstable_get_next_instance(
  const u32_t *column,
  struct snmp_obj_id *row_oid,
  struct
  snmp_node_instance *cell_instance)
{
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(channel_erro_flags_table_oid_ranges)];
  size_t i;

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp,
                     LWIP_ARRAYSIZE(channel_erro_flags_table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  for (i = 1; i <= LWIP_ARRAYSIZE(GetSRuntimePtr()->SaChannelErrors); i++)
  {
    u32_t test_oid[LWIP_ARRAYSIZE(channel_erro_flags_table_oid_ranges)];

    test_oid[0] = i;

    /* check generated OID: is it a candidate for the next one? */
    snmp_next_oid_check(&state, test_oid,
                        LWIP_ARRAYSIZE(channel_erro_flags_table_oid_ranges),
                        (void *) i);
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS)
  {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    cell_instance->reference.u32 = LWIP_CONST_CAST(u32_t, state.reference);

    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}

static s16_t kgmchannelerrorflagstable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value)
{
  s16_t value_len;
  u32_t i = cell_instance->reference.u32 - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 1:
      {
        /* kgmErrorFlagsGroupNumber */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaChannelErrors[i].bNumber;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* kgmRedLampAllFailure */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaChannelErrors[i].bRedLampFailure;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* kgmGreenLampAllFailure */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaChannelErrors[i].bGreenLampFailure;
        value_len = sizeof(s32_t);
        break;
      }

      case 4:
      {
        /* kgmYellowLampAllFailure */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaChannelErrors[i].bYellowLampFailure;
        value_len = sizeof(s32_t);
        break;
      }

      case 5:
      {
        /* kgmUndesiredRedSignal */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaChannelErrors[i].bUndesiredRedLamp;
        value_len = sizeof(s32_t);
        break;
      }

      case 6:
      {
        /* kgmUndesiredGreenSignal */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaChannelErrors[i].bUndesiredGreenLamp;
        value_len = sizeof(s32_t);
        break;
      }

      case 7:
      {
        /* kgmUndesiredYellowSignal */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaChannelErrors[i].bUndesiredYellowLamp;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmchannelerrorflagstable_get_value(): unknown id: %"S32_F
                     "\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* kgmchannelerrorflagstable_get_value */

static s16_t kgmchannel_treenode_get_value(struct snmp_node_instance *instance,
                                           void *value)
{
  s16_t value_len;

  switch (instance->node->oid)
  {
      case 1:
      {
        /* kgmMaxTrffcLghtFltStatusGroups */
        s32_t *v = (s32_t *) value;

        *v = SIGNAL_GROUPS_MAX;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* kgmMaxChannelErrorFlagsGroups */
        s32_t *v = (s32_t *) value;

        *v = SIGNAL_GROUPS_MAX / 8;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmchannel_treenode_get_value(): unknown id: %"S32_F"\n",
                     instance->node->oid));
        value_len = 0;
        break;
      }
  }

  return value_len;
}

/* --- kgmSignalState 1.3.6.1.4.1.59873.4.2.1.3 ----------------------------------------------------- */
static snmp_err_t kgmsignalstatetable_get_instance(const u32_t *column,
                                                   const u32_t *row_oid,
                                                   u8_t row_oid_len,
                                                   struct snmp_node_instance *
                                                   cell_instance)
{
  u8_t i;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid, row_oid_len, signal_state_table_oid_ranges,
                         LWIP_ARRAYSIZE(signal_state_table_oid_ranges)))
  {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif index from incoming OID */
  i = row_oid[0];

  /* find netif with index */
  if (i <= LWIP_ARRAYSIZE(GetSRuntimePtr()->SaSignalStateRuntimes))
  {
    cell_instance->reference.u32 = (u32_t) (i);

    return SNMP_ERR_NOERROR;
  }

  return SNMP_ERR_NOSUCHINSTANCE;
}

static snmp_err_t kgmsignalstatetable_get_next_instance(const u32_t *column,
                                                        struct snmp_obj_id *
                                                        row_oid,
                                                        struct
                                                        snmp_node_instance *
                                                        cell_instance)
{
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(signal_state_table_oid_ranges)];
  size_t i;

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state,
                     row_oid->id,
                     row_oid->len,
                     result_temp,
                     LWIP_ARRAYSIZE(signal_state_table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  for (i = 1; i <= LWIP_ARRAYSIZE(GetSRuntimePtr()->SaSignalStateRuntimes); i++)
  {
    u32_t test_oid[LWIP_ARRAYSIZE(signal_state_table_oid_ranges)];

    test_oid[0] = i;

    /* check generated OID: is it a candidate for the next one? */
    snmp_next_oid_check(&state,
                        test_oid,
                        LWIP_ARRAYSIZE(signal_state_table_oid_ranges),
                        (void *) i);
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS)
  {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    cell_instance->reference.u32 = LWIP_CONST_CAST(u32_t, state.reference);

    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}

static s16_t kgmsignalstatetable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value)
{
  s16_t value_len;
  char strData[4];
  u32_t i = cell_instance->reference.u32 - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 1:
      {
        /* kgmSignalStateNumber */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSignalStateRuntimes[i].bNumber;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* kgmSignalStatePatternNo */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSignalStateRuntimes[i].bPatternNo;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* kgmSignalStateExecMode */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSignalStateRuntimes[i].bExecutionMode;
        value_len = sizeof(s32_t);
        break;
      }

      case 4:
      {
        /* kgmSignalStatePlanMode */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSignalStateRuntimes[i].bPlanMode;
        value_len = sizeof(s32_t);
        break;
      }

      case 5:
      {
        /* kgmSignalStateStructure */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSignalStateRuntimes[i].bSetNo;
        value_len = sizeof(s32_t);
        break;
      }

      case 6:
      {
        /* kgmSignalStatePlan */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSignalStateRuntimes[i].bPlanNo;
        value_len = sizeof(s32_t);
        break;
      }

      case 7:
      {
        /* kgmSignalStatePhase */
        memset(strData, 0, sizeof(strData));
        sprintf(strData,
                "%d",
                GetSRuntimePtr()->SaSignalStateRuntimes[i].bPhaseNo);
        value_len = strlen(strData);
        if (value_len <= SNMP_MAX_VALUE_SIZE)
        {
          memcpy(value, strData, value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      case 8:
      {
        /* kgmSignalStateNextPhase */
        memset(strData, 0, sizeof(strData));
        sprintf(strData,
                "%d",
                GetSRuntimePtr()->SaSignalStateRuntimes[i].bNextPhase);
        value_len = strlen(strData);
        if (value_len <= SNMP_MAX_VALUE_SIZE)
        {
          memcpy(value, strData, value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      case 9:
      {
        /* kgmSignalStateStep */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSignalStateRuntimes[i].bStepNo;
        value_len = sizeof(s32_t);
        break;
      }

      case 10:
      {
        /* kgmSignalStateTransitionFlag */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSignalStateRuntimes[i].fIsTransitionStep;
        value_len = sizeof(s32_t);
        break;
      }

      case 11:
      {
        /* kgmSignalStateTransitionStep */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSignalStateRuntimes[i].bTransitionStepNo;
        value_len = sizeof(s32_t);
        break;
      }

      case 12:
      {
        /* kgmSignalStateElapsedTime */
        memset(strData, 0, sizeof(strData));
        sprintf(strData,
                "%d",
                GetSRuntimePtr()->SaSignalStateRuntimes[i].bElapsedTime);
        value_len = strlen(strData);
        if (value_len <= SNMP_MAX_VALUE_SIZE)
        {
          memcpy(value, strData, value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      case 13:
      {
        /* kgmSignalStateRemainingTime */
        memset(strData, 0, sizeof(strData));
        sprintf(strData,
                "%d",
                GetSRuntimePtr()->SaSignalStateRuntimes[i].bRemainingTime);
        value_len = strlen(strData);
        if (value_len <= SNMP_MAX_VALUE_SIZE)
        {
          memcpy(value,
                 strData,
                 value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      case 14:
      {
        /* kgmSignalStateStepTime */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSignalStateRuntimes[i].bStepTime;
        value_len = sizeof(s32_t);
        break;
      }

      case 15:
      {
        /* kgmSignalStateCycleTime */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSignalStateRuntimes[i].bCycleTime;
        value_len = sizeof(s32_t);
        break;
      }

      case 16:
      {
        /* kgmTrPatternTimeToNextCycle */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->SaSignalStateRuntimes[i].bTimeToNexCycle;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmsignalstatetable_get_value(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* kgmsignalstatetable_get_value */

static s16_t kgmsignalstate_treenode_get_value(
  struct snmp_node_instance *instance,
  void *value)
{
  s16_t value_len;

  switch (instance->node->oid)
  {
      case 1:
      {
        /* kgmMaxSignalState */
        s32_t *v = (s32_t *) value;

        *v = SIGNAL_STATES_MAX;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* kgmSignalPlanLastChangeTimes */
        u32_t *v = (u32_t *) value;

        *v = GetSRuntimePtr()->lPlanLastChangeTime;
        value_len = sizeof(u32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmsignalstate_treenode_get_value(): unknown id: %"S32_F
                     "\n", instance->node->oid));
        value_len = 0;
        break;
      }
  }

  return value_len;
}

/* --- kgmTrPattern 1.3.6.1.4.1.59873.4.2.1.4 ----------------------------------------------------- */
static snmp_err_t kgmtrpatterntable_get_instance(const u32_t *column,
                                                 const u32_t *row_oid,
                                                 u8_t row_oid_len,
                                                 struct snmp_node_instance *
                                                 cell_instance)
{
  u8_t i, j;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid, row_oid_len, tr_pattern_table_oid_ranges,
                         LWIP_ARRAYSIZE(tr_pattern_table_oid_ranges)))
  {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  i = row_oid[0];
  j = row_oid[1];

  if (i <= LWIP_ARRAYSIZE(GetSTRPatternsAndCoordsPtr()->SaaPatterns))
  {
    if (j <= LWIP_ARRAYSIZE(GetSTRPatternsAndCoordsPtr()->SaaPatterns[i]))
    {
      return SNMP_ERR_NOERROR;
    }
  }

  return SNMP_ERR_NOSUCHINSTANCE;
}

static snmp_err_t kgmtrpatterntable_get_next_instance(const u32_t *column,
                                                      struct snmp_obj_id *
                                                      row_oid,
                                                      struct snmp_node_instance
                                                      *cell_instance)
{
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(tr_pattern_table_oid_ranges)];
  u8_t i;
  u8_t j;

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state,
                     row_oid->id,
                     row_oid->len,
                     result_temp,
                     LWIP_ARRAYSIZE(tr_pattern_table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  for (i = 1;
       i <= LWIP_ARRAYSIZE(GetSTRPatternsAndCoordsPtr()->SaaPatterns);
       i++)
  {
    for (j = 1;
         j <= LWIP_ARRAYSIZE(GetSTRPatternsAndCoordsPtr()->SaaPatterns[i]);
         j++)
    {
      u32_t test_oid[LWIP_ARRAYSIZE(tr_pattern_table_oid_ranges)];

      test_oid[0] = i;
      test_oid[1] = j;
      snmp_next_oid_check(&state, test_oid,
                          LWIP_ARRAYSIZE(tr_pattern_table_oid_ranges), NULL);
    }
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS)
  {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);

    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}

static s16_t kgmtrpatterntable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value)
{
  s16_t value_len;
  u32_t *oid = cell_instance->instance_oid.id;
  u32_t i = oid[2] - 1;
  u32_t j = oid[3] - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 1:
      {
        /* kgmSubjunctionNumber */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].bSubjunctionNo;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* kgmTrPatternNumber */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].bPatternNo;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* kgmTrPatternPriority */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].bPriority;
        value_len = sizeof(s32_t);
        break;
      }

      case 4:
      {
        /* kgmTrPatternPlanMode */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].bPlanMode;
        value_len = sizeof(s32_t);
        break;
      }

      case 5:
      {
        /* kgmTrPatternExtendedMode */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].bExtendedMode;
        value_len = sizeof(s32_t);
        break;
      }

      case 6:
      {
        /* kgmTrPatternSequenceNumber */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].bSequenceNo;
        value_len = sizeof(s32_t);
        break;
      }

      case 7:
      {
        /* kgmTrPatternSplitNumber */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].bSplitNo;
        value_len = sizeof(s32_t);
        break;
      }

      case 8:
      {
        /* kgmTrPatternCoordStatus */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].fCoordStatus;
        value_len = sizeof(s32_t);
        break;
      }

      case 9:
      {
        /* kgmTrPatternOutputSupervision */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].fOutputSupervision;
        value_len = sizeof(s32_t);
        break;
      }

      case 10:
      {
        /* kgmTrPatternSpecParamTableOID */
        value_len =
          GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].
          bSpecialParamTableOIDLength;
        if (value_len <= SNMP_MAX_VALUE_SIZE)
        {
          memcpy(value,
                 GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].
                 laSpecialParamTablOID,
                 value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmtrpatterntable_get_value(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* kgmtrpatterntable_get_value */

static snmp_err_t kgmtrpatterntable_set_test(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_WRONGVALUE;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 4:
      {
        /* kgmTrPatternPlanMode */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 1) && (*v <= 8)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 7:
      {
        /* kgmTrPatternSplitNumber */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 1) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 8:
      {
        /* kgmTrPatternCoordStatus */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 9:
      {
        /* kgmTrPatternOutputSupervision */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 10:
      {
        /* kgmTrPatternSpecParamTableOID */

        err = SNMP_ERR_NOERROR;
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmtrpatterntable_set_test(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        break;
      }
  } /* switch */

  return err;
} /* kgmtrpatterntable_set_test */

static snmp_err_t kgmtrpatterntable_set_value(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_NOERROR;
  u32_t *oid = cell_instance->instance_oid.id;
  u32_t i = oid[2] - 1;
  u32_t j = oid[3] - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 4:
      {
        /* kgmTrPatternPlanMode */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].bPlanMode = *v;
        if (j == SigProgCurNoGet() - 1)
        {
          switch (*v)
          {
              case PATTERN_PLAN_MODE_FLASING:
              {
                UserStateReqSet(STATES_FLASH);
                break;
              }

              case PATTERN_PLAN_MODE_DARK:
              {
                UserStateReqSet(STATES_NO_CONTROL);
                break;
              }

              default:
              {
                UserStateReqFree();
                break;
              }
          }
        }

        break;
      }

      case 7:
      {
        /* kgmTrPatternSplitNumber */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].bSplitNo = *v;
        break;
      }

      case 8:
      {
        /* kgmTrPatternCoordStatus */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].fCoordStatus = *v;
        break;
      }

      case 9:
      {
        /* kgmTrPatternOutputSupervision */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].fOutputSupervision = *v;
        break;
      }

      case 10:
      {
        /* kgmTrPatternSpecParamTableOID */
        u32_t *v = (u32_t *) value;
        u8_t v_len = len;

        memset(
          GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].laSpecialParamTablOID,
          0,
          sizeof(GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].
                 laSpecialParamTablOID));
        memcpy(
          GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].laSpecialParamTablOID,
          v,
          v_len);
        GetSTRPatternsAndCoordsPtr()->SaaPatterns[i][j].
        bSpecialParamTableOIDLength = v_len;
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmtrpatterntable_set_value(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        break;
      }
  } /* switch */

  return err;
} /* kgmtrpatterntable_set_value */

static snmp_err_t kgmtrcoordtable_get_instance(const u32_t *column,
                                               const u32_t *row_oid,
                                               u8_t row_oid_len,
                                               struct snmp_node_instance *
                                               cell_instance)
{
  u8_t i;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid,
                         row_oid_len,
                         tr_coord_table_oid_ranges,
                         LWIP_ARRAYSIZE(tr_coord_table_oid_ranges)))
  {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif index from incoming OID */
  i = row_oid[0];

  /* find netif with index */
  if (i <= LWIP_ARRAYSIZE(GetSTRPatternsAndCoordsPtr()->SaCoords))
  {
    cell_instance->reference.u32 = (u32_t) (i);

    return SNMP_ERR_NOERROR;
  }

  return SNMP_ERR_NOSUCHINSTANCE;
}

static snmp_err_t kgmtrcoordtable_get_next_instance(const u32_t *column,
                                                    struct snmp_obj_id *row_oid,
                                                    struct snmp_node_instance *
                                                    cell_instance)
{
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(tr_coord_table_oid_ranges)];
  size_t i;

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state,
                     row_oid->id,
                     row_oid->len,
                     result_temp,
                     LWIP_ARRAYSIZE(tr_coord_table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  for (i = 1; i <= LWIP_ARRAYSIZE(GetSTRPatternsAndCoordsPtr()->SaCoords); i++)
  {
    u32_t test_oid[LWIP_ARRAYSIZE(tr_coord_table_oid_ranges)];

    test_oid[0] = i;

    /* check generated OID: is it a candidate for the next one? */
    snmp_next_oid_check(&state, test_oid,
                        LWIP_ARRAYSIZE(tr_coord_table_oid_ranges), (void *) i);
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS)
  {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    cell_instance->reference.u32 = LWIP_CONST_CAST(u32_t, state.reference);

    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}

static s16_t kgmtrcoordtable_get_value(struct snmp_node_instance *cell_instance,
                                       void *value)
{
  s16_t value_len;
  u32_t i = cell_instance->reference.u32 - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 1:
      {
        /* kgmTrCoordNumber */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaCoords[i].bIdx;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* kgmTrCoordCycleTime */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaCoords[i].sCycleTime;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* kgmTrCoordGeneralOffsetTime */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaCoords[i].sGeneralOffsetTime;
        value_len = sizeof(s32_t);
        break;
      }

      case 4:
      {
        /* kgmTrCoordPhaseId01 */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaCoords[i].bPhaseId01;
        value_len = sizeof(s32_t);
        break;
      }

      case 5:
      {
        /* kgmTrCoordPhase01minDuration */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaCoords[i].bPhase01MinDuration;
        value_len = sizeof(s32_t);
        break;
      }

      case 6:
      {
        /* kgmTrCoordOffset01 */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaCoords[i].bOffset01;
        value_len = sizeof(s32_t);
        break;
      }

      case 7:
      {
        /* kgmTrCoordReturnPhaseId01 */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaCoords[i].bReturnPhaseId01;
        value_len = sizeof(s32_t);
        LWIP_UNUSED_ARG(v);
        break;
      }

      case 8:
      {
        /* kgmTrCoordPhaseId02 */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaCoords[i].bPhaseId02;
        value_len = sizeof(s32_t);
        LWIP_UNUSED_ARG(v);
        break;
      }

      case 9:
      {
        /* kgmTrCoordPhase02minDuration */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaCoords[i].bPhase02MinDuration;
        value_len = sizeof(s32_t);
        LWIP_UNUSED_ARG(v);
        break;
      }

      case 10:
      {
        /* kgmTrCoordOffset02 */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaCoords[i].bOffset02;
        value_len = sizeof(s32_t);
        break;
      }

      case 11:
      {
        /* kgmTrCoordReturnPhaseId02 */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->SaCoords[i].bReturnPhaseId02;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmtrcoordtable_get_value(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* kgmtrcoordtable_get_value */

static snmp_err_t kgmtrcoordtable_set_test(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_WRONGVALUE;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 2:
      {
        /* kgmTrCoordCycleTime */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 65535)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 3:
      {
        /* kgmTrCoordGeneralOffsetTime */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 65535)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 4:
      {
        /* kgmTrCoordPhaseId01 */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 5:
      {
        /* kgmTrCoordPhase01minDuration */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 6:
      {
        /* kgmTrCoordOffset01 */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 7:
      {
        /* kgmTrCoordReturnPhaseId01 */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 8:
      {
        /* kgmTrCoordPhaseId02 */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 9:
      {
        /* kgmTrCoordPhase02minDuration */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 10:
      {
        /* kgmTrCoordOffset02 */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      case 11:
      {
        /* kgmTrCoordReturnPhaseId02 */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 255)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmtrcoordtable_set_test(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        break;
      }
  } /* switch */

  return err;
} /* kgmtrcoordtable_set_test */

static snmp_err_t kgmtrcoordtable_set_value(
  struct snmp_node_instance *cell_instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_NOERROR;

  LWIP_UNUSED_ARG(len);
  u32_t i = cell_instance->reference.u32 - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 2:
      {
        /* kgmTrCoordCycleTime */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaCoords[i].sCycleTime = *v;
        break;
      }

      case 3:
      {
        /* kgmTrCoordGeneralOffsetTime */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaCoords[i].sGeneralOffsetTime = *v;
        break;
      }

      case 4:
      {
        /* kgmTrCoordPhaseId01 */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaCoords[i].bPhaseId01 = *v;
        break;
      }

      case 5:
      {
        /* kgmTrCoordPhase01minDuration */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaCoords[i].bPhase01MinDuration = *v;
        break;
      }

      case 6:
      {
        /* kgmTrCoordOffset01 */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaCoords[i].bOffset01 = *v;
        break;
      }

      case 7:
      {
        /* kgmTrCoordReturnPhaseId01 */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaCoords[i].bReturnPhaseId01 = *v;
        break;
      }

      case 8:
      {
        /* kgmTrCoordPhaseId02 */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaCoords[i].bPhaseId02 = *v;
        break;
      }

      case 9:
      {
        /* kgmTrCoordPhase02minDuration */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaCoords[i].bPhase02MinDuration = *v;
        break;
      }

      case 10:
      {
        /* kgmTrCoordOffset02 */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaCoords[i].bOffset02 = *v;
        break;
      }

      case 11:
      {
        /* kgmTrCoordReturnPhaseId02 */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->SaCoords[i].bReturnPhaseId02 = *v;
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmtrcoordtable_set_value(): unknown id: %"S32_F"\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        break;
      }
  } /* switch */

  return err;
} /* kgmtrcoordtable_set_value */

static s16_t kgmtrpattern_treenode_get_value(
  struct snmp_node_instance *instance,
  void *value)
{
  s16_t value_len;

  switch (instance->node->oid)
  {
      case 1:
      {
        /* kgmMaxSubjunctions */
        s32_t *v = (s32_t *) value;

        *v = TR_PATTERNS_SUBJUNCTIONS_MAX;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* kgmMaxTrPatterns */
        s32_t *v = (s32_t *) value;

        *v = TR_PATERNS_MAX;
        value_len = sizeof(s32_t);
        break;
      }

      case 4:
      {
        /* kgmMaxTrCoords */
        s32_t *v = (s32_t *) value;

        *v = TR_COORDS_MAX;
        value_len = sizeof(s32_t);
        break;
      }

      case 6:
      {
        /* kgmSignalPlanUpgrade */
        s32_t *v = (s32_t *) value;

        *v = GetSTRPatternsAndCoordsPtr()->fSignalPlanUpgrade;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmtrpattern_treenode_get_value(): unknown id: %"S32_F
                     "\n", instance->node->oid));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* kgmtrpattern_treenode_get_value */

static snmp_err_t kgmtrpattern_treenode_set_test(
  struct snmp_node_instance *instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_WRONGVALUE;

  switch (instance->node->oid)
  {
      case 6:
      {
        /* kgmSignalPlanUpgrade */
        s32_t *v = (s32_t *) value;

        LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
        if (((*v >= 0) && (*v <= 1)))
        {
          err = SNMP_ERR_NOERROR;
        }

        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmtrpattern_treenode_set_test(): unknown id: %"S32_F"\n",
                     instance->node->oid));
        break;
      }
  }

  return err;
}

static snmp_err_t kgmtrpattern_treenode_set_value(
  struct snmp_node_instance *instance,
  u16_t len,
  void *value)
{
  snmp_err_t err = SNMP_ERR_NOERROR;

  LWIP_UNUSED_ARG(len);
  switch (instance->node->oid)
  {
      case 6:
      {
        /* kgmSignalPlanUpgrade */
        s32_t *v = (s32_t *) value;

        GetSTRPatternsAndCoordsPtr()->fSignalPlanUpgrade = *v;
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmtrpattern_treenode_set_value(): unknown id: %"S32_F
                     "\n", instance->node->oid));
        break;
      }
  }

  return err;
}

/* --- kgmUser 1.3.6.1.4.1.59873.4.2.1.6 ----------------------------------------------------- */
static snmp_err_t kgmuseroperationstable_get_instance(const u32_t *column,
                                                      const u32_t *row_oid,
                                                      u8_t row_oid_len,
                                                      struct snmp_node_instance
                                                      *cell_instance)
{
  u8_t i;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid, row_oid_len, user_operations_table_oid_ranges,
                         LWIP_ARRAYSIZE(user_operations_table_oid_ranges)))
  {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif index from incoming OID */
  i = row_oid[0];

  /* find netif with index */
  if (i <= LWIP_ARRAYSIZE(GetSUserOperationsPtr()->SaOperations))
  {
    cell_instance->reference.u32 = (u32_t) (i);

    return SNMP_ERR_NOERROR;
  }

  return SNMP_ERR_NOSUCHINSTANCE;
}

static snmp_err_t kgmuseroperationstable_get_next_instance(const u32_t *column,
                                                           struct snmp_obj_id *
                                                           row_oid,
                                                           struct
                                                           snmp_node_instance *
                                                           cell_instance)
{
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(user_operations_table_oid_ranges)];
  size_t i;

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state,
                     row_oid->id,
                     row_oid->len,
                     result_temp,
                     LWIP_ARRAYSIZE(user_operations_table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  for (i = 1; i <= LWIP_ARRAYSIZE(GetSUserOperationsPtr()->SaOperations); i++)
  {
    u32_t test_oid[LWIP_ARRAYSIZE(user_operations_table_oid_ranges)];

    test_oid[0] = i;

    /* check generated OID: is it a candidate for the next one? */
    snmp_next_oid_check(&state, test_oid,
                        LWIP_ARRAYSIZE(user_operations_table_oid_ranges),
                        (void *) i);
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS)
  {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    cell_instance->reference.u32 = LWIP_CONST_CAST(u32_t, state.reference);

    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}

static s16_t kgmuseroperationstable_get_value(
  struct snmp_node_instance *cell_instance,
  void *value)
{
  s16_t value_len;
  u32_t i = cell_instance->reference.u32 - 1;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
      case 1:
      {
        /* kgmUserOperationsNumber */
        s32_t *v = (s32_t *) value;

        *v = GetSUserOperationsPtr()->SaOperations[i].bIdx;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* kgmUserOperationsType */
        s32_t *v = (s32_t *) value;

        *v = GetSUserOperationsPtr()->SaOperations[i].bType;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* kgmUserOperationsTime */
        u32_t *v = (u32_t *) value;

        *v = GetSUserOperationsPtr()->SaOperations[i].lTime;
        value_len = sizeof(u32_t);
        LWIP_UNUSED_ARG(v);
        break;
      }

      case 4:
      {
        /* kgmUserOperationsULoginName */
        value_len =
          sizeof(GetSUserOperationsPtr()->SaOperations[i].strUsername);
        if ((value_len <= SNMP_MAX_VALUE_SIZE))
        {
          memcpy(value,
                 GetSUserOperationsPtr()->SaOperations[i].strUsername,
                 value_len);
        }
        else
        {
          value_len = 0;
        }

        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmuseroperationstable_get_value(): unknown id: %"S32_F
                     "\n",
                     SNMP_TABLE_GET_COLUMN_FROM_OID(
                       cell_instance->instance_oid.id)));
        value_len = 0;
        break;
      }
  } /* switch */

  return value_len;
} /* kgmuseroperationstable_get_value */

static s16_t kgmuser_treenode_get_value(struct snmp_node_instance *instance,
                                        void *value)
{
  s16_t value_len;

  switch (instance->node->oid)
  {
      case 1:
      {
        /* kgmMaxUserOperations */
        s32_t *v = (s32_t *) value;

        *v = USER_OPERATIONS_MAX;
        value_len = sizeof(s32_t);
        break;
      }

      case 3:
      {
        /* kgmUserListFileUpdate */
        s32_t *v = (s32_t *) value;

        *v = GetSUserOperationsPtr()->fIsUpdated;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmuser_treenode_get_value(): unknown id: %"S32_F"\n",
                     instance->node->oid));
        value_len = 0;
        break;
      }
  }

  return value_len;
}

/* --- kgmAsc 1.3.6.1.4.1.59873.4.2.1 ----------------------------------------------------- */
static s16_t kgmmoduleerrorstatus_scalars_get_value(
  const struct snmp_scalar_array_node_def *node,
  void *value)
{
  s16_t value_len;

  switch (node->oid)
  {
      case 1:
      {
        /* kgmMaxDriverModuleGroupStatus */
        s32_t *v = (s32_t *) value;

        *v = GetSCPPtr()->SConsumed.bSSMTotal;
        value_len = sizeof(s32_t);
        break;
      }

      case 2:
      {
        /* kgmDriverModuleGroupStatus */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->sSSMStatus;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    (
                      "kgmmoduleerrorstatus_scalars_get_value(): unknown id: %"S32_F
                      "\n", node->oid));
        value_len = 0;
        break;
      }
  }

  return value_len;
}

static s16_t kgmdetector_scalars_get_value(
  const struct snmp_scalar_array_node_def *node,
  void *value)
{
  s16_t value_len;

  switch (node->oid)
  {
      case 1:
      {
        /* kgmDedectorModuleStatus */
        s32_t *v = (s32_t *) value;

        *v = GetSRuntimePtr()->sLDMStatus;
        value_len = sizeof(s32_t);
        break;
      }

      default:
      {
        LWIP_DEBUGF(SNMP_MIB_DEBUG,
                    ("kgmdetector_scalars_get_value(): unknown id: %"S32_F"\n",
                     node->oid));
        value_len = 0;
        break;
      }
  }

  return value_len;
}

/* --- kgmDevices 1.3.6.1.4.1.59873.4.2 ----------------------------------------------------- */
/* --- kgmTransportation 1.3.6.1.4.1.59873.4 ----------------------------------------------------- */
/* --- kgm  ----------------------------------------------------- */
#endif /* LWIP_SNMP */
