/*
 *  Generated by LwipMibCompiler
 */

#ifndef TC_KGM_V0_7_H
#define TC_KGM_V0_7_H TC_KGM_V0_7_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp_core.h"

extern const struct snmp_mib kgm;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP */
#endif /* TC_KGM_V0_7_H */
